Repository Nexmo/nexmo-developer, pull requests merged in 2018-06, with the labels that each got.

#555 Improved Python code style for message signing examples
  _examples/messaging/signing-messages/check-response/Python
  _examples/messaging/signing-messages/create-request/Python
  _examples/messaging/signing-messages/validate-signature/Python
Labels: stale

#729 Update chatapp error codes
  _open_api/errors/messages-and-workflows-apis/messages.md
Labels: waiting-for-reporter

#741 Various improvements.
  _documentation/messages-and-workflows-apis/messages/building-blocks/send-a-viber-service-message.md
  _documentation/messages-and-workflows-apis/messages/building-blocks/send-an-sms-with-messages-api.md
  _documentation/messages-and-workflows-apis/messages/building-blocks/send-with-facebook-messenger.md
  _documentation/messages-and-workflows-apis/messages/guides/facebook-messenger.md
  _documentation/messages-and-workflows-apis/messages/guides/sms-messages.md
  _documentation/messages-and-workflows-apis/messages/guides/viber-service-messages.md
  _documentation/messages-and-workflows-apis/messages/overview.md
  _documentation/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover.md
  _documentation/messages-and-workflows-apis/workflows/guides/failover.md
  _documentation/messages-and-workflows-apis/workflows/overview.md
Labels: messages-workflows-api

#719 Add report API format guides
  _documentation/reporting/overview.md
  _documentation/reporting/tutorial.md
  public/assets/images/figure 1.png
  public/assets/images/figure 2.png
  public/assets/images/figure 3.png
  public/assets/images/figure 4.png
Labels: waiting-for-reporter

#763 Tony messages workflows fixes - WIP
  _documentation/messages-and-workflows-apis/messages/building-blocks/send-a-viber-service-message.md
  _documentation/messages-and-workflows-apis/messages/building-blocks/send-an-sms-with-messages-api.md
  _documentation/messages-and-workflows-apis/messages/guides/facebook-messenger.md
  _documentation/messages-and-workflows-apis/messages/guides/sms-messages.md
  _documentation/messages-and-workflows-apis/messages/guides/viber-service-messages.md
  _documentation/messages-and-workflows-apis/messages/overview.md
  _documentation/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover.md
  _documentation/messages-and-workflows-apis/workflows/guides/failover.md
  _documentation/messages-and-workflows-apis/workflows/overview.md
  config/locales/en.yml
  config/navigation.yml
  config/notices.yml
Labels: messages-workflows-api
