Repository Nexmo/nexmo-developer, pull requests merged in 2018-11, with the labels that each got.

#1148 Call Tracking Voice Tutorial: Updated
  _tutorials/call-tracking.md
Labels: ready for review

#1163 Add note that US numbers don't return portability/reachability info
  _documentation/number-insight/building-blocks/number-insight-standard.md
  _documentation/number-insight/overview.md
Labels: ready for review

#1197 Fix mailto links in SMS DLR guide
  _documentation/messaging/sms/guides/delivery-receipts.md
Labels: ready for review

#1192 Simplification of tutorials plus external account linking.
  _documentation/messages/building-blocks/before-you-begin.md
  _documentation/messages/building-blocks/configure-webhooks.md
  _documentation/messages/concepts/facebook.md
  _documentation/messages/concepts/whatsapp.md
  _partials/reusable/configure-webhook-urls.md
  _partials/reusable/create-a-nexmo-application.md
  _partials/reusable/generate-a-jwt.md
  _partials/reusable/link-facebook-to-nexmo.md
  _partials/reusable/prereqs.md
  _tutorials/sending-facebook-message-with-failover.md
  _tutorials/sending-facebook-messenger-messages-with-messages-api.md
  _tutorials/sending-sms-messages-with-messages-api.md
  _tutorials/sending-viber-service-messages-with-messages-api.md
  _tutorials/sending-whatsapp-messages-with-messages-api.md
Labels: messages-dispatch-api, ready for review

#1228 Fix issue #1216 - typo.
  _partials/reusable/prereqs.md
Labels: ready for review

#1213 Initial draft of guest blog landing page
  app/controllers/static_controller.rb
  app/views/static/developer_spotlight.html.erb
  app/views/static/team.html.erb
  config/routes.rb
  public/assets/images/developer_spotlight.png
  public/assets/images/developer_spotlight_logo.png
Labels: don't merge

#1230 Require comment for negative feedback
  app/javascript/packs/Feedback.jsx
Labels: ready for review

#1229 Add new SMS API concatenation tutorial
  _tutorials/receiving-concat-sms.md
Labels: ready for review

#1255 The Beta version of CLI supports creating Messages and Dispatch apps.
  _documentation/dispatch/building-blocks/before-you-begin.md
  _documentation/dispatch/concepts/install-cli.md
  _documentation/messages/building-blocks/before-you-begin.md
  _documentation/messages/concepts/install-cli.md
  _partials/reusable/install-beta-cli.md
  _partials/reusable/link-facebook-to-nexmo.md
  _partials/reusable/prereqs.md
Labels: messages-dispatch-api

#1258 Create app using CLI
  _documentation/dispatch/building-blocks/client-library.md
  _documentation/dispatch/building-blocks/create-an-application.md
  _documentation/dispatch/building-blocks/install-cli.md
  _documentation/dispatch/concepts/workflows.md
  _documentation/messages/building-blocks/client-library.md
  _documentation/messages/building-blocks/configure-webhooks.md
  _documentation/messages/building-blocks/create-an-application.md
  _documentation/messages/building-blocks/inbound-message.md
  _documentation/messages/building-blocks/install-cli.md
  _documentation/messages/building-blocks/message-status.md
  _documentation/messages/building-blocks/send-an-sms-with-messages-api.md
  _documentation/messages/concepts/external-accounts.md
  _documentation/messages/concepts/facebook.md
  _documentation/messages/concepts/viber.md
  _documentation/messages/concepts/whatsapp.md
  _partials/reusable/configure-webhook-urls.md
  _partials/reusable/create-a-nexmo-application.md
  _partials/reusable/link-facebook-to-nexmo.md
  app/views/building_blocks/_application_messages_dispatch.html.erb
  config/redirects.yml
Labels: ready for review

#1046 Attempt to describe signature generation.
  _documentation/concepts/guides/signing-messages.md
  _documentation/concepts/overview.md
  _examples/messaging/signing-messages/check-response/Node
  _examples/messaging/signing-messages/check-response/PHP
  _examples/messaging/signing-messages/check-response/Python
  _examples/messaging/signing-messages/check-response/Ruby
  _examples/messaging/signing-messages/create-request/Node
  _examples/messaging/signing-messages/create-request/PHP
  _examples/messaging/signing-messages/create-request/Python
  _examples/messaging/signing-messages/create-request/Ruby
  _examples/messaging/signing-messages/validate-signature/Node
  _examples/messaging/signing-messages/validate-signature/PHP
  _examples/messaging/signing-messages/validate-signature/Python
  _examples/messaging/signing-messages/validate-signature/Ruby
  app/views/static/documentation.md
Labels: ready for review

#1268 Clarifications on webhooks.
  _documentation/messages/building-blocks/before-you-begin.md
  _documentation/messages/building-blocks/configure-webhooks.md
  _documentation/messages/building-blocks/inbound-message.md
  _documentation/messages/building-blocks/message-status.md
  _partials/reusable/configure-webhook-urls.md
  _partials/reusable/create-a-nexmo-application.md
  _partials/reusable/prereqs.md
Labels: messages-dispatch-api, ready for review
