Repository Nexmo/nexmo-developer, pull requests merged in 2018-07, with the labels that each got.

#733 adding stitch in-app video
  _documentation/stitch/in-app-video/guides/1-enable-video.md
  _documentation/stitch/in-app-video/guides/2-enable-screenshare.md
  _documentation/stitch/in-app-video/overview.md
  _partials/stitch/guides/5-calling-users/javascript.md
  _partials/stitch/guides/6-enable-video/javascript.md
  _partials/stitch/guides/7-enable-screenshare/javascript.md
  app/assets/fonts/icomoon.eot
  app/assets/fonts/icomoon.svg
  app/assets/fonts/icomoon.ttf
  app/assets/fonts/icomoon.woff
  app/assets/fonts/nexmo-developer.json
  app/assets/stylesheets/_icons.scss
  app/views/static/_products.html.erb
  config/locales/en.yml
  config/navigation.yml
Labels: don't merge

#753 Tony contribs review
  app/views/contribute/guides/code-examples.md
  app/views/contribute/guides/introduction.md
  app/views/contribute/guides/platform.md
  app/views/contribute/guides/styleguide.md
  app/views/contribute/guides/write-the-docs.md
  app/views/contribute/overview.md
  app/views/contribute/structure/guides/building-blocks.md
  app/views/contribute/structure/guides/guides.md
  app/views/contribute/structure/guides/overviews.md
  app/views/contribute/structure/guides/tutorials.md
  app/views/contribute/structure/overview.md
Labels: ready for review

#805 VAPI docs fixes.
  .gitignore
  .vscode/settings.json
  _documentation/voice/voice-api/guides/legs-conversations.md
  _documentation/voice/voice-api/guides/ncco.md
  _documentation/voice/voice-api/overview.md
  _examples/voice/ncco/creating-a-custom-call-or-conversation-for-each-user/Python
Labels: ready for review

#819 Documentation for working with building blocks
  _examples/concepts/sample-building-block/java.yml
  _examples/concepts/sample-building-block/node.yml
  _examples/concepts/sample-building-block/php.yml
  _examples/concepts/sample-building-block/python.yml
  _examples/concepts/sample-building-block/ruby.yml
  app/views/contribute/building-blocks/sample-building-block.md
  app/views/contribute/structure/guides/building-blocks.md
  public/assets/images/contributing/building-block-anatomy.png
Labels: ready for review

#842 Add JWT ACL description
  _documentation/stitch/concepts/jwt-acl.md
Labels: pending
