Repository Nexmo/nexmo-developer, pull requests merged in 2019-04, with the labels that each got.

#1615 Client SDK docs reorg
  _documentation/client-sdk/in-app-voice/getting-started/app-to-app-call.md
  _documentation/client-sdk/in-app-voice/getting-started/make-phone-call.md
  _documentation/client-sdk/in-app-voice/getting-started/receive-phone-call.md
  _documentation/client-sdk/in-app-voice/guides/call-statuses.md
  _documentation/client-sdk/in-app-voice/guides/enable-audio.md
  _documentation/client-sdk/in-app-voice/guides/inbound-pstn.md
  _documentation/client-sdk/in-app-voice/guides/ncco-guide.md
  _documentation/client-sdk/in-app-voice/guides/send-and-receive-dtmf.md
  _documentation/client-sdk/in-app-voice/onboarding.md
  _documentation/client-sdk/in-app-voice/overview.md
  _documentation/client-sdk/setup/add-sdk-to-your-app.md
  _documentation/client-sdk/setup/set-up-push-notifications.md
  _documentation/conversation/concepts/jwt-acl.md
  _partials/stitch/guides/enable-audio/javascript.md
  _tabbed/getting-started/app-to-app-call/android.md
  _tabbed/getting-started/app-to-app-call/ios.md
  _tabbed/getting-started/make-phone-call/android.md
  _tabbed/getting-started/make-phone-call/ios.md
  _tabbed/getting-started/make-phone-call/javascript.md
  _tabbed/getting-started/receive-phone-call/android.md
  _tabbed/getting-started/receive-phone-call/ios.md
  _tabbed/getting-started/receive-phone-call/javascript.md
  _tabbed/setup/add-sdk-to-your-app/android.md
  _tabbed/setup/add-sdk-to-your-app/ios.md
  _tabbed/setup/add-sdk-to-your-app/javascript.md
  _tabbed/setup/set-up-push-notifications/android.md
  _tabbed/setup/set-up-push-notifications/ios.md
  app/views/static/_products.html.erb
  config/locales/en.yml
  config/navigation.yml
  config/stitch-redirects.yml
Labels: ready for review

#1617 Add Github action to auto-deploy Heroku review app
  .github/main.workflow
Labels: review-app

#1523 Combine CodeLanguageResolver with CodeLanguage
  app/constraints/documentation_constraint.rb
  app/constraints/open_api_constraint.rb
  app/controllers/application_controller.rb
  app/controllers/tutorials_controller.rb
  app/filters/code_snippet_filter.rb
  app/filters/code_snippets_filter.rb
  app/filters/tab_filter.rb
  app/models/code_language.rb
  app/services/code_language_resolver.rb
  app/views/open_api/show.html.erb
  config/routes.rb
  spec/models/code_language_spec.rb
  spec/services/code_language_resolver_spec.rb
Labels: review-app

#1620 FBM product info
  _tutorials/fbm-product-info.md
Labels: messages-dispatch-api, review-app

#1627 Fix OAS array response field rendering
  app/views/open_api/_response_description_parameters.html.erb
Labels: review-app

#1628 Add PHP Yorkshire landing page
  config/landing_pages/e/phpyorkshire.yml
Labels: review-app

#1632 Add local setup instructions for OSX
  README.md
Labels: review-app

#1634 Add Fabian Rodriguez to the team page.
  config/team.yml
Labels: review-app

#1633 Upgrade Volta
  README.md
  app/assets/volta/README.md
  app/assets/volta/scss/components/_badge.scss
  app/assets/volta/scss/components/_buttons.scss
  app/assets/volta/scss/components/_callouts.scss
  app/assets/volta/scss/components/_card.scss
  app/assets/volta/scss/components/_color-classes.scss
  app/assets/volta/scss/components/_dropdowns.scss
  app/assets/volta/scss/components/_flash-messages.scss
  app/assets/volta/scss/components/_form-elements.scss
  app/assets/volta/scss/components/_lists.scss
  app/assets/volta/scss/components/_tables.scss
  app/assets/volta/scss/components/side-navigation/_side-nav--aqua.scss
  app/assets/volta/scss/components/side-navigation/_side-nav--dark.scss
  app/assets/volta/scss/components/side-navigation/_side-nav--light.scss
  app/assets/volta/scss/layout/_utils.scss
  app/assets/volta/scss/lib/_type.scss
  app/assets/volta/scss/lib/_variables.scss
  app/assets/volta/scss/volta.scss
Labels: review-app

#1640 Clarify omission of leading plus symbol for E164 format
  _documentation/concepts/guides/glossary.md
Labels: ready for review, review-app

#1642 Update with WhatsApp Media support
  _documentation/messages/overview.md
Labels: review-app

#1644 Add support for inbound video
  _documentation/messages/overview.md
Labels: review-app

#1649 Refactor Modals to use Volta
  app/assets/javascripts/application.js
  app/assets/stylesheets/_settings.scss
  app/assets/stylesheets/_typography.scss
  app/assets/stylesheets/nexmo.scss
  app/filters/modal_filter.rb
  app/javascript/packs/Modals.js
  app/javascript/packs/application.js
  app/views/layouts/api.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/documentation-index.html.erb
  app/views/layouts/documentation.html.erb
  app/views/layouts/page.html.erb
  app/views/layouts/static.html.erb
  spec/filters/modal_filter_spec.rb
Labels: review-app

#1647 Add JWT dependency to curl building blocks
  _examples/voice/make-an-outbound-call/curl.yml
  app/filters/code_snippet_filter.rb
  app/services/code_snippet_renderer/curl.rb
  app/views/code_snippets/_dependencies.html.erb
Labels: ready for review

#1637 Add Framework Libraries to NDP Tools Page
  app/views/static/tools.html.erb
Labels: review-app

#1650 Use JWT dependency for curl voice snippets
  _examples/voice/download-a-recording/curl.yml
  _examples/voice/earmuff-a-call/curl.yml
  _examples/voice/make-an-outbound-call-with-ncco/curl.yml
  _examples/voice/mute-a-call/curl.yml
  _examples/voice/play-an-audio-stream-into-a-call/curl.yml
  _examples/voice/play-dtmf-into-a-call/curl.yml
  _examples/voice/play-tts-into-a-call/curl.yml
  _examples/voice/retrieve-info-for-a-call/curl.yml
  _examples/voice/retrieve-info-for-all-calls/curl.yml
  _examples/voice/transfer-a-call/curl.yml
Labels: ready for review, review-app

#1635 Smoke api error urls
  .travis.yml
  Gemfile
  Gemfile.lock
  app/constraints/open_api_constraint.rb
  app/controllers/api_errors_controller.rb
  app/controllers/open_api_controller.rb
  config/api-errors.yml
  config/routes.rb
  lib/tasks/ci.rake
Labels: review-app

#1639 Rewrite Numbers overview and guides
  _documentation/numbers/guides/enable-2fa.md
  _documentation/numbers/guides/event-alerts.md
  _documentation/numbers/guides/number-management.md
  _documentation/numbers/guides/numbers-cli.md
  _documentation/numbers/guides/numbers.md
  _documentation/numbers/guides/payments.md
  _documentation/numbers/overview.md
Labels: ready for review, review-app

#1651 Add Ringback key to onAnswer in NCCO ref
  _documentation/voice/voice-api/ncco-reference.md
Labels: review-app

#1641 Real-time data feeds using Messages API
  _tutorials/fbm-product-info.md
  _tutorials/real-time-feed.md
Labels: review-app

#1656 Switch career page URL from Bamboo to new portal
  app/views/static/team.html.erb
Labels: review-app

#1654 Check for migration pending Rails error in CI rake tasks
  lib/common_errors.rb
  lib/tasks/ci.rake
  spec/lib/common_errors_spec.rb
Labels: review-app

#1646 RailsConf Landing Page
  app/views/static/default_landing/partials/_header.html.erb
  config/landing_pages/e/railsconf.yml
Labels: review-app

#1658 Add Hotjar for usage tracking
  app/views/layouts/partials/_head.html.erb
Labels: review-app

#1661 Pin node version to 8 < x <=10 for node-gyp compatability
  package.json
Labels: review-app

#1662 Clarify bargeIn behaviour for NCCO Talk and Stream
  _documentation/voice/voice-api/ncco-reference.md
Labels: review-app

#1659 Add Product Lifecycle pages
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/views/product-lifecycle/beta.md
  app/views/product-lifecycle/developer-preview.md
  config/locales/en.yml
  config/routes.rb
  spec/smoke_spec.rb
Labels: review-app

#1663 Fix broken links
  _documentation/conversation/overview.md
  _documentation/messaging/sms/code-snippets/before-you-begin.md
  _documentation/messaging/sms/code-snippets/receiving-an-sms.md
  _documentation/messaging/us-short-codes/guides/2fa.md
  _documentation/messaging/us-short-codes/guides/alerts.md
  _documentation/number-insight/code-snippets/before-you-begin.md
  _documentation/verify/code-snippets/before-you-begin.md
  _documentation/verify/code-snippets/trigger-next-verification-process.md
  _documentation/voice/voice-api/code-snippets/before-you-begin.md
  _documentation/vonage-business-cloud/vbc-apis/getting-started/create-application.md
  _examples/concepts/sample-code-snippet/java.yml
  _examples/concepts/sample-code-snippet/node.yml
  _examples/concepts/sample-code-snippet/php.yml
  _examples/concepts/sample-code-snippet/python.yml
  _examples/concepts/sample-code-snippet/ruby.yml
  _partials/client-sdk/voice/link-nexmo-number.md
  _tutorials/client-sdk-ios-in-app-messaging.md
  app/services/code_snippet_renderer/objective_c.rb
  app/services/code_snippet_renderer/swift.rb
  app/views/contribute/guides/code-examples.md
  app/views/contribute/guides/writing-style-guide.md
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#1665 client sdk getting started: fix broken links, make links absolute
  _tabbed/guides/start-and-receive-in-app-calls/android.md
  _tabbed/guides/start-and-receive-in-app-calls/ios.md
  _tabbed/guides/start-and-receive-in-app-calls/javascript.md
Labels: review-app

#1664 Dispatch API use case
  _tutorials/dispatch-user-fallback.md
Labels: review-app

#1668 Change check yarn integrity in webpacker to false in development
  config/webpacker.yml
Labels: review-app

#1666 Add link to blog post on RailsConf landing page
  config/landing_pages/e/railsconf.yml
Labels: review-app

#1671 Add nexmo_rails library to tools page
  app/views/static/tools.html.erb
Labels: review-app
