Repository Nexmo/nexmo-developer, pull requests merged in 2019-10, with the labels that each got.

#2020 Added transfer with NCCO example for PHP
  _examples/voice/transfer-a-call-inline-ncco/php.yml
Labels: review-app

#2023 Remove Alumni Section
  app/views/static/team.html.erb
  config/team.yml
  spec/features/team_spec.rb
Labels: review-app

#2022 Add more roles to approved Greenhouse list
  app/services/greenhouse.rb
Labels: review-app

#2027 Add redirect for application code snippets
  config/redirects.yml
Labels: review-app

#2028 Add documentation to list of allowed Greenhouse roles
  app/services/greenhouse.rb
Labels: review-app

#2011 Migrate NDP from React to Vuej.s
  app/assets/stylesheets/layout/_print.scss
  app/javascript/components/concatenation/Concatenation.vue
  app/javascript/components/concatenation/index.js
  app/javascript/components/feedback/Feedback.vue
  app/javascript/components/feedback/index.js
  app/javascript/components/jwt_generator/JwtGenerator.vue
  app/javascript/components/jwt_generator/index.js
  app/javascript/components/search/NDPArticle.vue
  app/javascript/components/search/Search.vue
  app/javascript/components/search/ZendeskArticle.vue
  app/javascript/components/search/index.js
  app/javascript/packs/application.js
  app/javascript/volta_tabbed_examples/index.js
  app/views/layouts/landing.html.erb
  app/views/layouts/partials/_feedback.html.erb
  app/views/layouts/partials/_head.html.erb
  app/views/layouts/partials/_header.html.erb
  app/views/static/jwt.html.erb
  app/views/tools/concatenation.html
  babel.config.js
  config/webpack/environment.js
  config/webpack/loaders/vue.js
  config/webpacker.yml
  package.json
  spec/javascript/components/concatenation/Concatenation.test.js
  spec/javascript/components/feedback/Feedback.test.js
  spec/javascript/components/jwt_generator/JwtGenerator.test.js
  spec/javascript/components/search/NDPArticle.test.js
  spec/javascript/components/search/Search.test.js
  spec/javascript/components/search/ZendeskArticle.test.js
  spec/javascript/fixtures/emptySearch.js
  spec/javascript/fixtures/search.js
  spec/javascript/setupJest.js
  yarn.lock
Labels: review-app

#2004 Initial draft of App v2 CLI support
  _documentation/application/nexmo-cli.md
  _documentation/application/overview.md
  _examples/application/create-application/node.yml
  _examples/application/delete-application/node.yml
  _examples/application/get-application/node.yml
  _examples/application/list-applications/node.yml
  _examples/application/update-application/node.yml
Labels: review-app

#2031 Add Campus landing page
  config/landing_pages/campus.yml
Labels: review-app

#2029 Search NDP on request query path to improve 404 results
  app/controllers/application_controller.rb
  app/views/static/404.html.erb
Labels: review-app

#2034 Fix horizontal scrolling for campus banner
  app/views/layouts/partials/_notices.html.erb
Labels: review-app

#2037 Add linkable elements and speaker bios to Campus page
  config/landing_pages/campus.yml
Labels: review-app

#2039 Adding link to bios from image in sessions
  config/landing_pages/campus.yml
Labels: review-app

#2026 Upgrades to Node 12 to fix Webpacker error
  .nvmrc
  .travis.yml
  README.md
  package.json
Labels: review-app

#2040 Make Contact Center Guide a Use Case
  _documentation/client-sdk/in-app-voice/overview.md
  _use_cases/contact-center-client-sdk.md
  config/redirects.yml
Labels: review-app

#2035 Add a list of language definitions for Verify API
  _documentation/verify/guides/verify-languages.md
Labels: review-app

#2043 Convert Setup guides to tabbed folder guides
  .spelling
  _documentation/client-sdk/in-app-voice/concepts/call-statuses.md
  _documentation/client-sdk/setup/add-sdk-to-your-app.md
  _documentation/client-sdk/setup/add-sdk-to-your-app/.config.yml
  _documentation/client-sdk/setup/add-sdk-to-your-app/android.md
  _documentation/client-sdk/setup/add-sdk-to-your-app/ios.md
  _documentation/client-sdk/setup/add-sdk-to-your-app/javascript.md
  _documentation/client-sdk/setup/create-your-application.md
  _documentation/client-sdk/setup/set-up-push-notifications.md
  _documentation/client-sdk/setup/set-up-push-notifications/.config.yml
  _documentation/client-sdk/setup/set-up-push-notifications/android.md
  _documentation/client-sdk/setup/set-up-push-notifications/ios.md
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2054 Updating post images on Spotlight landing page
  config/landing_pages/spotlight.yml
Labels: review-app

#2055 Clarify wording in the endOnExit NCCO reference
  _documentation/voice/voice-api/ncco-reference.md
Labels: review-app

#2056 Product is client sdk
  _use_cases/contact-center-client-sdk.md
Labels: review-app

#2053 Check for `meta_title` and `description` Rake task for documentation
  lib/tasks/documentation.rake
Labels: review-app

#2052 Additions to Application Overview
  _documentation/application/overview.md
Labels: review-app

#2058 Rewording for endOnExit
  _documentation/voice/voice-api/ncco-reference.md
Labels: review-app

#2064 Add YAML for Ruby Record a Conversation snippet
  _documentation/conversation/code-snippets/conversation/record-conversation.md
  _examples/conversation/conversation/record-conversation/ruby.yml
Labels: review-app

#2069 Fix typo and minor tweaks in Voice overview
  _documentation/voice/voice-api/overview.md
Labels: review-app

#2077 Modifying prerequisite steps on app-to-phone/phone-to-app tutorials
  config/tutorials/app-to-phone.yml
  config/tutorials/phone-to-app.yml
Labels: review-app

#2072 Update Dockerfile to match the required node version.
  Dockerfile
Labels: review-app

#2032 Tutorial revisions
  _tutorials/buy-nexmo-number.md
  _tutorials/client-sdk/app-to-phone-code.md
  _tutorials/client-sdk/create-application.md
  _tutorials/client-sdk/create-user.md
  _tutorials/client-sdk/create-webhook-server-app-to-phone.md
  _tutorials/client-sdk/create-webhook-server-phone-to-app.md
  _tutorials/client-sdk/generate-jwt.md
  _tutorials/client-sdk/phone-to-app-code.md
  _tutorials/client-sdk/run-app-to-phone.md
  _tutorials/client-sdk/run-phone-to-app.md
  _tutorials/create-nexmo-account.md
  _tutorials/install-express.md
  _tutorials/install-node-client-sdk.md
  _tutorials/link-nexmo-number.md
  _tutorials/run-ngrok.md
  app/views/tutorial/_prerequisites.html.erb
  config/tutorials/app-to-phone.yml
  config/tutorials/phone-to-app.yml
  public/assets/screenshots/tutorials/app-to-phone/nexmo-dashboard-applications.png
Labels: review-app

#2078 Add different options for A/B testing the signup button.
  app/views/layouts/partials/_header.html.erb
Labels: review-app

#2080 In app voice make a phone call changes
  _partials/client-sdk/voice/javascript/hangup.md
  _partials/client-sdk/voice/javascript/login.md
Labels: review-app

#2082 Update WhatsApp overview
  _documentation/messages/concepts/whatsapp.md
Labels: review-app

#2083 Add folks to teams page
  config/team.yml
  spec/features/team_spec.rb
Labels: review-app

#2079 Clarification for number used in App-to-Phone
  _tabbed/getting-started/make-phone-call/javascript.md
Labels: review-app

#2085 Rename ConversationClient to NexmoClient
  _documentation/client-sdk/in-app-voice/guides/start-and-receive-calls/javascript.md
  _partials/stitch/guides/enable-screenshare/javascript.md
Labels: review-app

#2087 Update JS Release Notes for v6.0.2
  _documentation/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2081 Linking a Facebook Page to a Nexmo application
  _partials/reusable/link-facebook-to-nexmo.md
Labels: review-app

#2096 Update SDK docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#2095 Update JS Release Notes for v6.0.3
  _documentation/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2050 Upgrade Rails to v6.0
  Gemfile
  Gemfile.lock
  app/filters/php_inliner_filter.rb
  app/pipelines/markdown_pipeline.rb
  config/application.rb
  db/migrate/20191022100247_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb
  db/schema.rb
  spec/controllers/feedback/feedbacks_controller_spec.rb
  spec/filters/php_inliner_filter_spec.rb
Labels: review-app

#2090 Link to tutorials from strategic locations.
  _documentation/client-sdk/in-app-messaging/guides/inviting-members.md
  _documentation/client-sdk/in-app-messaging/guides/simple-conversation.md
  _documentation/client-sdk/in-app-messaging/guides/utilizing-events.md
  _documentation/client-sdk/in-app-voice/getting-started/make-phone-call.md
  _documentation/client-sdk/in-app-voice/getting-started/receive-phone-call.md
  _documentation/client-sdk/in-app-voice/guides/start-and-receive-calls/javascript.md
Labels: review-app

#2098 Fix the JWT generator.
  app/javascript/components/jwt_generator/JwtGenerator.vue
Labels: review-app

#2038 First draft of Click to Call use case
  _use_cases/client-sdk-click-to-call.md
Labels: review-app

#2061 Sendinblue use case
  _use_cases/client-sdk-sendinblue-order-confirm.md
Labels: review-app

#2101 Fix incorrect git clone command
  _use_cases/client-sdk-click-to-call.md
Labels: review-app

#2104 Mark MEMBER_ID as optional in custom events
  _documentation/conversation/code-snippets/event/create-custom-event.md
Labels: review-app

#2103 Update Opentok video product links
  app/views/static/_products.html.erb
  spec/features/landing_page_spec.rb
Labels: review-app

#2093 Add links to Tutorials and Use Cases for Client SDK
  app/views/static/_products.html.erb
  spec/features/landing_page_spec.rb
Labels: Ready for Review, review-app

#2008 add info on media templates
  _documentation/messages/code-snippets/whatsapp/send-media-mtm.md
Labels: Ready for Review, review-app

#2107 Add the OAS_PATH env var for the docker setup
  docker-compose.yml
Labels: review-app

#2110 Creating app is first step
  app/views/static/_products.html.erb
  spec/features/landing_page_spec.rb
Labels: Ready for Review, review-app

#2106 Client SDK Digital Marketplace Application Use Case
  _use_cases/digital-marketplace-client-sdk.md
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/api-key-and-secret.png
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/app-listing-item-for-sale.png
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/app-login.png
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/create-an-application.png
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/private-key-location-glitch.png
  public/assets/screenshots/use-cases/digital-marketplace-client-sdk/private-key-location-local.png
Labels: review-app

#2105 Add support for a list of disallowed words
  .disallowed_words
  .travis.yml
  _documentation/client-sdk/troubleshooting.md
  _documentation/voice/voice-api/ncco-reference.md
  lib/tasks/ci.rake
Labels: review-app

#2057 Remove Account Secret Management content duplication
  _documentation/account/secret-management.md
  _documentation/account/secret-management/code-snippets/create-a-secret.md
  _documentation/account/secret-management/code-snippets/fetch-a-secret.md
  _documentation/account/secret-management/code-snippets/list-all-secrets.md
  _documentation/account/secret-management/code-snippets/revoke-a-secret.md
  config/redirects.yml
Labels: review-app

#2074 Remove constraints from renderer.
  .travis.yml
  Gemfile
  Gemfile.lock
  app/constraints/open_api_constraint.rb
  app/controllers/api_errors_controller.rb
  config/api-errors.yml
  config/redirects.yml
  lib/tasks/ci.rake
Labels: review-app

#2115 Upgrade OAS Renderer to 0.6.4
  Gemfile
  Gemfile.lock
Labels: review-app

#2118 Bump nexmo-oas-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2120 Fix redirect.
  config/redirects.yml
Labels: review-app

#2121 [DEVX-1459] Prevent nested tabs from changing the url.
  app/javascript/volta_tabbed_examples/index.js
Labels: review-app

#2116 Update Campus banner
  app/views/layouts/partials/_notices.html.erb
Labels: WIP - Don't Merge, review-app

#2123 Add initializer to Geocoder and specify a timeout.
  config/initializers/geocoder.rb
Labels: review-app
