Repository Nexmo/nexmo-developer, pull requests merged in 2019-11, with the labels that each got.

#2127 Added IP_ADDRESS placeholder to sample request URL
  _documentation/number-insight/guides/ip-matching.md
Labels: review-app

#2126 Fix feedback component.
  app/javascript/components/feedback/Feedback.vue
  spec/javascript/components/feedback/Feedback.test.js
Labels: review-app

#2130 Remove Campus banner
  app/views/layouts/partials/_notices.html.erb
  public/assets/campus/banner_background.png
  public/assets/campus/icon.svg
Labels: review-app

#2128 Add gem `barnes`.
  Gemfile
  Gemfile.lock
  config/puma.rb
Labels: review-app

#2131 Conversation API is Beta
  config/navigation.yml
Labels: review-app

#2137 Revert "Change Form to a pdf link for requesting Reports API pricing."
  _documentation/reports/overview.md
  public/assets/pdf/reports/NEXMO-REPORTSBETA_PRICING.pdf
Labels: review-app

#2136 Fixes a bunch of 404 and adds redirects
  _documentation/client-sdk/in-app-voice/getting-started/app-to-app-call/ios.md
  _documentation/client-sdk/in-app-voice/getting-started/make-phone-call/ios.md
  _documentation/client-sdk/in-app-voice/getting-started/receive-phone-call/ios.md
  _documentation/messaging/sms/code-snippets/delivery-receipts.md
  _documentation/messaging/sms/code-snippets/receiving-an-sms.md
  _use_cases/contact-center-client-sdk.md
  _use_cases/real-time-feed.md
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2140 Prevent tabs to be focused by default and making the page scroll.
  vendor/assets/javascripts/volta/components/volta.tab.js
Labels: review-app

#2138 Move ip-messaging tasks under a subfolder.
  _tutorials/client-sdk/ip-messaging/add-users-to-conversation.md
  _tutorials/client-sdk/ip-messaging/authenticate-users.md
  _tutorials/client-sdk/ip-messaging/create-ui.md
  _tutorials/client-sdk/ip-messaging/create-users.md
  _tutorials/client-sdk/ip-messaging/generate-jwts.md
  _tutorials/client-sdk/ip-messaging/join-conversation.md
  _tutorials/client-sdk/ip-messaging/run-application.md
  _tutorials/client-sdk/ip-messaging/send-message.md
  _tutorials/client-sdk/ip-messaging/show-message-history.md
  _tutorials/client-sdk/ip-messaging/typing-indicators.md
  app/controllers/tutorial_controller.rb
  config/tutorials/in-app-messaging.yml
Labels: review-app

#2109 Add documentation for new Verify Workflows
  _documentation/verify/guides/workflows-and-events.md
Labels: review-app

#2134 add rubyconf landing page
  config/landing_pages/e/rubyconf.yml
Labels: review-app

#2144 Update ncco-reference.md
  _documentation/voice/voice-api/ncco-reference.md
Labels: review-app

#2143 Add Reports API to API listing page
  app/views/api/index.html.erb
Labels: review-app

#2142 [DEVX-1747] Update Android Push to FCMV1
  _documentation/client-sdk/setup/set-up-push-notifications/android.md
Labels: review-app

#2148 Add a note that there may be a delay.
  _documentation/messaging/sms/code-snippets/delivery-receipts.md
Labels: review-app

#2147 Update README.md and config/database.yml.
  .env.example
  README.md
  config/database.yml
Labels: review-app

#2155 Improved delivery receipt note
  _documentation/messaging/sms/code-snippets/delivery-receipts.md
Labels: review-app

#2160 moved iOS & Obj-C partials to own folder
  _documentation/client-sdk/setup/set-up-push-notifications/ios.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/device-token/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/device-token/swift.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/enable-notifications-voip/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/enable-notifications-voip/swift.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/enable-notifications/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/enable-notifications/swift.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/incoming/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/incoming/swift.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/pushkit-delegate-voip/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/pushkit-delegate-voip/swift.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/pushkit/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/pushkit/swift.md
Labels: review-app

#2141 [DEVX-1735] Use Mermaid.js default styles.
  app/javascript/packs/application.js
Labels: review-app

#2163 Remove duplicate redirects.
  config/stitch-redirects.yml
Labels: review-app

#2162 update android docs
  public/sdk/stitch/android
Labels: WIP - Don't Merge, review-app

#2169 Update JS Release Notes for v6.0.4
  _documentation/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2173 Update SDK docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#2175 Conversation API is Beta not dev preview
  _documentation/conversation/overview.md
Labels: review-app

#2154 Add OAS3 pricing API
  _api/developer/pricing.md
  app/constraints/open_api_constraint.rb
  config/redirects.yml
Labels: Ready for Review, review-app

#2166 Add 8kHz rate for websocket endpoint
  _documentation/voice/voice-api/ncco-reference.md
Labels: Ready for Review, review-app

#2168 Client SDK data centre configuration
  _documentation/client-sdk/setup/configure-data-center.md
Labels: Ready for Review, review-app

#2172 Remove IP matching from Number Insight
  _documentation/number-insight/guides/ip-matching.md
  _documentation/number-insight/guides/number-insight-via-cli.md
  _documentation/number-insight/overview.md
  config/redirects.yml
Labels: review-app

#2178 Small change to update where user name is located
  _documentation/client-sdk/in-app-voice/getting-started/receive-phone-call/javascript.md
Labels: review-app

#2179 Update RubyConf landing page
  config/landing_pages/e/rubyconf.yml
Labels: review-app

#2181 Rename verify_nexmo_signature to nexmo_rack
  config/landing_pages/e/rubyconf.yml
Labels: review-app

#2189 RubyConf landing page update of Rack middleware description
  config/landing_pages/e/rubyconf.yml
Labels: review-app

#2194 Update SDK docs
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
Labels: review-app

#2197 points iOS docs to the latest version
  public/sdk/stitch/ios
Labels: review-app

#2198 Update release notes Android 1.0.3
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: i18n fixed

#2199 Reorganize Client SDK tutorial material into sub-folder
  _tutorials/en/client-sdk/app-to-phone/code.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server.md
  _tutorials/en/client-sdk/app-to-phone/run.md
  _tutorials/en/client-sdk/phone-to-app/code.md
  _tutorials/en/client-sdk/phone-to-app/create-webhook-server.md
  _tutorials/en/client-sdk/phone-to-app/run.md
  config/tutorials/en/app-to-phone.yml
  config/tutorials/en/phone-to-app.yml
Labels: Ready for Review, i18n fixed, review-app

#2180 Improve Data Center configuration topic
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/ios.md
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/javascript.md
  _documentation/en/client-sdk/setup/configure-data-center.md
  _examples/client-sdk/dc-config/android.md
  _examples/client-sdk/dc-config/javascript.md
Labels: Ready for Review, i18n fixed, review-app

#2192 Update JS Release Notes for v6.0.5
  .spelling
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: i18n fixed, review-app

#2207 Add new A/B test for header CTA
  app/views/layouts/partials/_header.html.erb
Labels: review-app

#2133 Cache sidenav
  Procfile
  app/helpers/application_helper.rb
  app/javascript/navigation/index.js
  app/presenters/sidenav_subitem.rb
  app/views/layouts/documentation.html.erb
  app/views/layouts/partials/_sidenav_subitem.html.erb
  config/environments/development.rb
  lib/tasks/cache.rake
  spec/presenters/sidenav_subitem_spec.rb
Labels: review-app

#2185 You might get a delivery receipt
  _documentation/en/messaging/sms/code-snippets/delivery-receipts.md
Labels: Ready for Review, i18n fixed, review-app

#2174 [DEVX-1601] Add visitor id to logs
  app/middleware/nexmo_developer/visitor_id.rb
  config/application.rb
Labels: review-app

#2187 Initial Ngrok topic plus change links
  _documentation/en/concepts/guides/testing-with-ngrok.md
  _documentation/en/concepts/guides/webhooks.md
  _documentation/en/messaging/sms/code-snippets/before-you-begin.md
  _documentation/en/number-insight/code-snippets/before-you-begin.md
  _partials/reusable/configure-webhook-urls.md
  _tutorials/en/client-sdk/create-application.md
  _tutorials/en/olympus/test-webhook-server.md
  _use_cases/en/fraud-scoring-and-phone-number-verification.md
  _use_cases/en/interactive-voice-response.md
  _use_cases/en/local-numbers.md
  _use_cases/en/voice-alerts.md
  config/redirects.yml
Labels: Ready for Review, i18n fixed, review-app

#2205 Note on text and media sizes for WhatsApp
  _documentation/en/messages/code-snippets/whatsapp/send-audio.md
  _documentation/en/messages/code-snippets/whatsapp/send-file.md
  _documentation/en/messages/code-snippets/whatsapp/send-image.md
  _documentation/en/messages/code-snippets/whatsapp/send-text.md
  _documentation/en/messages/code-snippets/whatsapp/send-video.md
Labels: Ready for Review, review-app

#2184 Initial update for Client SDK create app topic
  .spelling
  _documentation/en/client-sdk/setup/create-your-application.md
Labels: Ready for Review, i18n fixed, review-app

#2112 Initial changes for the careers page.
  app/assets/stylesheets/layout/_careers.scss
  app/assets/stylesheets/nexmo.scss
  app/controllers/careers_controller.rb
  app/controllers/static_controller.rb
  app/javascript/careers/index.js
  app/javascript/packs/application.js
  app/presenters/career.rb
  app/services/greenhouse.rb
  app/views/careers/index.html.erb
  app/views/layouts/partials/_footer.html.erb
  app/views/static/_career.html.erb
  app/views/static/team.html.erb
  config/greenhouse_departments.yml
  config/routes.rb
  spec/features/careers_spec.rb
  spec/features/team_spec.rb
  spec/services/greenhouse_spec.rb
  spec/smoke_spec.rb
Labels: review-app

#2208 ClientSDK iOS DC configuration
  _examples/client-sdk/dc-config/ios.md
Labels: review-app

#2204 Glossary: Server SDKs, Client SDK, Conversation API
  _documentation/en/concepts/guides/glossary.md
Labels: Ready for Review, review-app

#2212 Describe getEvents paging
  _partials/stitch/guides/utilizing-events/javascript.md
Labels: Ready for Review, review-app

#2216 Fix SearchTerms.
  app/services/search_terms.rb
Labels: review-app

#2073 Convert iOS guide to tutorial
  _documentation/en/client-sdk/in-app-messaging/guides/ios-in-app-messaging.md
  _tutorials/en/client-sdk/ios-in-app-messaging/add-user.md
  _tutorials/en/client-sdk/ios-in-app-messaging/create-conversation.md
  _tutorials/en/client-sdk/ios-in-app-messaging/get-conversation.md
  _tutorials/en/client-sdk/ios-in-app-messaging/get-event-updates.md
  _tutorials/en/client-sdk/ios-in-app-messaging/get-events.md
  _tutorials/en/client-sdk/ios-in-app-messaging/get-members.md
  _tutorials/en/client-sdk/ios-in-app-messaging/get-past-events.md
  _tutorials/en/client-sdk/ios-in-app-messaging/join-conversation.md
  _tutorials/en/client-sdk/ios-in-app-messaging/send-message-attachment.md
  _tutorials/en/client-sdk/ios-in-app-messaging/send-text.md
  config/redirects.yml
  config/stitch-redirects.yml
  config/tutorials/en/ios-in-app-messaging.yml
Labels: i18n fixed, review-app

#2224 Fix release notes for JS
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2225 Fix sdk docs
  _tutorials_tabbed_content/client-sdk/get-started/in-app-voice/in-app-calling-ios/call-type/objective-c.md
  _tutorials_tabbed_content/client-sdk/get-started/in-app-voice/in-app-calling-ios/started-project/objective-c.md
  _tutorials_tabbed_content/client-sdk/get-started/in-app-voice/in-app-calling-ios/started-project/swift.md
  _tutorials_tabbed_content/client-sdk/get-started/in-app-voice/outbound-pstn-ios/started-project/objective-c.md
  _tutorials_tabbed_content/client-sdk/get-started/in-app-voice/outbound-pstn-ios/started-project/swift.md
Labels: review-app

#2222 Update delivery receipt docs
  _documentation/en/messaging/sms/code-snippets/delivery-receipts.md
  _documentation/en/messaging/sms/guides/delivery-receipts.md
Labels: review-app

#2226 Make Message Search more prominent in TOC
  _documentation/en/messaging/sms/message-search/api-reference.md
  config/locales/en.yml
  config/redirects.yml
Labels: review-app

#2227 Remove backslash introduced by Smartling for some characters.
  app/filters/i18n/smartling_converter_filter.rb
  spec/filters/i18n/smartling_converter_spec.rb
Labels: review-app

#2223 Only render 404 results view if there are any results hits
  app/views/static/404.html.erb
Labels: review-app

#2228 Contact center fix
  _use_cases/en/contact-center-client-sdk.md
Labels: review-app

#2202 Programmable SIP - Initial draft
  _documentation/en/voice/sip/concepts/programmable-sip.md
  _documentation/en/voice/sip/concepts/sip-connect.md
  config/redirects.yml
Labels: Ready for Review, i18n fixed, review-app

#2230 Fix character counter
  app/javascript/components/concatenation/character_counter.js
  spec/javascript/components/concatenation/character_counter.test.js
Labels: review-app

#2232 Fix search when using the form without js.
  app/views/layouts/partials/_header.html.erb
Labels: review-app

#2233 Add additional curly brace options for top bar CTA A/B test
  app/views/layouts/partials/_header.html.erb
Labels: review-app
