Repository Nexmo/nexmo-developer, pull requests merged in 2019-05, with the labels that each got.

#1669 Add code examples to message signing docs
  _documentation/concepts/guides/signing-messages.md
  _examples/concepts/guides/send-signed-sms/php.yml
  _examples/concepts/guides/verify-signed-sms/php.yml
Labels: review-app

#1653 Clarify when completed status returned by a call
  _documentation/voice/voice-api/guides/call-flow.md
Labels: don't merge, review-app

#1674 Fix NDP sidebar keyboard navigation
  app/helpers/application_helper.rb
Labels: review-app

#1684 Make OAS response field toggle context aware
  app/javascript/packs/application.js
  app/views/open_api/_response_descriptions.html.erb
Labels: review-app

#1683 Fix code snippet dependency case issue
  app/filters/code_snippet_filter.rb
Labels: review-app

#1626 Send and Receive DTMF for iOS
  _documentation/client-sdk/in-app-voice/guides/send-and-receive-dtmf.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/receive/Kotlin.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/receive/Objective-C.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/receive/Swift.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/send/Kotlin.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/send/Objective-C.md
  _tutorials_tabbed_content/client-sdk/get-started/dtmf/send/Swift.md
  config/code_languages.yml
Labels: review-app

#1682 Make Messages Code Snippets collapsible
  _documentation/messages/code-snippets/messenger/send-text.md
  _documentation/messages/code-snippets/mms/send-mms.md
  _documentation/messages/code-snippets/sms/send-sms.md
  _documentation/messages/code-snippets/viber/send-text.md
  _documentation/messages/code-snippets/whatsapp/send-audio.md
  _documentation/messages/code-snippets/whatsapp/send-file.md
  _documentation/messages/code-snippets/whatsapp/send-image.md
  _documentation/messages/code-snippets/whatsapp/send-mtm.md
  _documentation/messages/code-snippets/whatsapp/send-text.md
  _documentation/messages/overview.md
  _examples/messages/messenger/send-text/curl.yml
  _examples/messages/messenger/send-text/node.yml
  _examples/messages/mms/send-mms/curl.yml
  _examples/messages/mms/send-mms/node.yml
  _examples/messages/sms/send-sms-basic-auth/curl.yml
  _examples/messages/sms/send-sms/curl.yml
  _examples/messages/sms/send-sms/node.yml
  _examples/messages/viber/send-text/curl.yml
  _examples/messages/viber/send-text/node.yml
  _examples/messages/whatsapp/send-audio/curl.yml
  _examples/messages/whatsapp/send-file/curl.yml
  _examples/messages/whatsapp/send-image/curl.yml
  _examples/messages/whatsapp/send-mtm/curl.yml
  _examples/messages/whatsapp/send-text/curl.yml
  _examples/messages/whatsapp/send-text/node.yml
  _tutorials/sending-facebook-messenger-messages-with-messages-api.md
  _tutorials/sending-sms-messages-with-messages-api.md
  _tutorials/sending-viber-service-messages-with-messages-api.md
  _tutorials/sending-whatsapp-messages-with-messages-api.md
  config/locales/en.yml
  config/navigation.yml
  config/redirects.yml
Labels: review-app

#1689 Remove developer preview label from VBC docs
  config/navigation.yml
Labels: review-app

#1690 Add Github action to auto-delete merged PRs
  .github/main.workflow
Labels: review-app

#1692 Color of dot next to Laravel framework library in tools page
  app/views/static/tools.html.erb
Labels: review-app

#1695 Add lograge log formatting in production
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: review-app

#1698 Fix .NET SMS code snippets
  _examples/messaging/sms/delivery-receipts/csharp.yml
  _examples/messaging/sms/receiving-an-sms/csharp.yml
  _examples/messaging/sms/send-an-sms-with-unicode/csharp.yml
Labels: ready for review, review-app

#1699 Highlight path parameters in API references
  app/assets/stylesheets/layout/_api.scss
  app/views/open_api/_endpoint.html.erb
Labels: review-app

#1700 Sammachin lex shutdown
  _documentation/voice/voice-api/guides/lex-connector.md
  _extend/amazon-lex-connector.md
  config/navigation.yml
Labels: review-app

#1648 Add inbound SIP answer_url docs
  _documentation/voice/sip/concepts/sip-connect.md
  _documentation/voice/voice-api/webhook-reference.md
  public/assets/images/workflow_sip_connect.png
Labels: review-app

#1463 New Config-Driven Community Page
  Gemfile
  Gemfile.lock
  app/admin/event.rb
  app/assets/javascripts/application.js
  app/assets/stylesheets/layout/_community.scss
  app/controllers/static_controller.rb
  app/helpers/video_helper.rb
  app/models/event.rb
  app/views/static/default_landing/partials/_contact_community.html.erb
  app/views/static/default_landing/partials/_event_search_results.js.erb
  app/views/static/default_landing/partials/_event_search_results_content.html.erb
  app/views/static/default_landing/partials/_event_search_results_map_content.html.erb
  app/views/static/default_landing/partials/_events.html.erb
  app/views/static/default_landing/partials/_featured_session.html.erb
  app/views/static/default_landing/partials/_header.html.erb
  app/views/static/default_landing/partials/_line_divider.html.erb
  app/views/static/default_landing/partials/_section_header.html.erb
  app/views/static/default_landing/partials/_sessions.html.erb
  app/views/static/default_landing/partials/_structured_text.html.erb
  config/landing_pages/community.yml
  config/routes.rb
  db/migrate/20190220092207_add_city_country_to_events.rb
  db/migrate/20190306130440_add_latitude_longitude_to_events.rb
  db/schema.rb
  db/seeds.rb
  spec/helpers/video_helper_spec.rb
  spec/views/static/default_landing/partials/_contact_community.html.erb_spec.rb
  spec/views/static/default_landing/partials/_events.html.erb_spec.rb
  spec/views/static/default_landing/partials/_featured_session.html.erb_spec.rb
  spec/views/static/default_landing/partials/_line_divider.html.erb_spec.rb
  vendor/assets/javascripts/underscore.js
Labels: don't merge

#1706 Add php|tek landing page
  config/landing_pages/e/phptek.yml
Labels: review-app

#1710 Add Nexmo Spring Boot Starter
  app/views/static/tools.html.erb
Labels: review-app

#1714 Remove references to free inbound SMS
  _documentation/messaging/sms/overview.md
Labels: review-app

#1724 Create jsconf-eu-coffee.yml
  config/landing_pages/e/jsconf-eu-coffee.yml
Labels: review-app

#1725 Update jsconf-eu-coffee.yml
  config/landing_pages/e/jsconf-eu-coffee.yml
Labels: review-app

#1726 Update jsconf-eu-coffee.yml
  config/landing_pages/e/jsconf-eu-coffee.yml
Labels: review-app
