Repository Nexmo/nexmo-developer, pull requests merged in 2020-04, with the labels that each got.

#2612 [CVE-2019-20149] Bump fix-to to fix security vulnerability
  package.json
  yarn.lock
Labels: review-app

#2617 Fix table
  _documentation/en/reports/overview.md
Labels: review-app

#2615 Disable map in community pages if there are no events with locations
  app/admin/event.rb
  app/controllers/static_controller.rb
  app/views/static/default_landing/partials/_events.html.erb
  db/migrate/20200402092734_add_remote_to_events.rb
  db/schema.rb
  spec/views/static/default_landing/partials/_events.html.erb_spec.rb
Labels: review-app

#2622 Add `Igor Wojda` to team page
  config/team.yml
Labels: review-app

#2624 Update Android Client-SDK dependency version
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
Labels: review-app

#2625 Fixed some copy that was still using Nexmo name
  _documentation/en/client-sdk/troubleshooting.md
  app/views/slack/join.html.erb
  app/views/static/_slack.html.erb
  app/views/static/community.html.erb
  spec/smoke_spec.rb
Labels: review-app

#2608 Update client library page
  _documentation/en/messages/code-snippets/client-library.md
  _documentation/en/messages/code-snippets/server-sdk.md
  _documentation/en/messaging/sms/code-snippets/before-you-begin.md
  _documentation/en/verify/code-snippets/before-you-begin.md
  _partials/reusable/beta-node-client-library-messages-dispatch.md
  _partials/reusable/beta-node-server-sdk-messages-dispatch.md
  _partials/reusable/generate-a-jwt.md
  _partials/reusable/prereqs.md
  _use_cases/en/fbm-product-info.md
  _use_cases/en/mobile-app-invites.md
  _use_cases/en/passwordless-authentication.md
  _use_cases/en/private-sms-communication.md
  _use_cases/en/real-time-feed.md
  _use_cases/en/sms-customer-support.md
  _use_cases/en/trancribe-amazon-api.md
  _use_cases/en/two-factor-authentication.md
  _use_cases/en/two-way-sms-for-customer-engagement.md
  _use_cases/en/validate-a-number.md
  app/views/contribute/guides/writing-style-guide.md
  app/views/product-lifecycle/dev-preview.md
  config/redirects.yml
Labels: review-app

#2602 Added subtopic for using Messages API Sandbox
  _documentation/en/messages/concepts/messages-api-sandbox.md
  _use_cases/en/sending-facebook-messenger-messages-with-messages-api.md
  _use_cases/en/sending-viber-service-messages-with-messages-api.md
  _use_cases/en/sending-whatsapp-messages-with-messages-api.md
  public/assets/images/messages/config-webhooks.png
Labels: Do Not Merge, review-app

#2630 Order videos by `created_at` in a descending fashion.
  app/controllers/static_controller.rb
  app/views/static/default_landing/partials/_sessions.html.erb
Labels: review-app

#2633 Add 32x32 favicon.
  app/views/layouts/partials/_head.html.erb
  public/favicon-32x32.png
Labels: review-app

#2636 Bump nexmo_markdown_renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2639 GitHub actions
  .github/workflows/ci.yml
  .travis.yml
  app/views/product-lifecycle/beta.md
  app/views/product-lifecycle/dev-preview.md
Labels: review-app

#2643 Update API product page as requested
  app/views/api/index.html.erb
Labels: review-app

#2641 iOS SDK release notes markdown conformance
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: Do Not Merge

#2649 Switch to ruby/setup-ruby
  .github/workflows/ci.yml
Labels: review-app

#2620 Update iOS SDK v2.1.8 release notes
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: review-app

#2654 Fix tutorials steps in the sidenav.
  app/views/tutorial/index.html.erb
Labels: review-app

#2662 Updates to redirects file
  config/redirects.yml
Labels: review-app

#2660 [DEVX-2493] Added send/receive guides
  _tutorials_tabbed_content/client-sdk/guides/messaging/receive-text/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/receive-text/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/send-text/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/send-text/kotlin.md
Labels: review-app

#2666 Fix spelling build failure
  .spelling
Labels: review-app

#2665 Bump nexmo-markdown-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2663 [DEVX-2718] Bump volta.
  package.json
  yarn.lock
Labels: review-app

#2657 Volta fixes
  app/views/api/index.html.erb
  app/views/layouts/partials/_header.html.erb
  app/views/static/_products.html.erb
  app/views/static/landing.html.erb
  app/webpacker/stylesheets/layout/_header.scss
  app/webpacker/stylesheets/objects/_navigation.scss
Labels: review-app

#2653 Update ruby version to 2.5.8.
  .github/workflows/ci.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: review-app

#2667 Devx 2494 snippet send receive image
  _tutorials_tabbed_content/client-sdk/guides/messaging/receive-images/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/receive-images/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/receive-text/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/send-images/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/send-images/kotlin.md
Labels: review-app

#2668 DEVX 2495 Added typing indicator snippets
  _tutorials_tabbed_content/client-sdk/guides/messaging/typing-indicators/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/typing-indicators/kotlin.md
Labels: review-app

#2661 Display `Kotlin` tab before `Java` tab
  config/code_languages.yml
Labels: review-app

#2670 [DEVX-2715] Drop opentok from tile.
  app/views/static/_products.html.erb
Labels: review-app

#2673 [DEVX-2729] Rebrand 'Nexmo Extend' to 'Vonage API Extend'.
  app/views/extend/index.html.erb
  spec/features/extend_spec.rb
  spec/smoke_spec.rb
Labels: review-app

#2590 Adding Glitch to the App to Phone tutorial
  _tutorials/en/client-sdk/app-to-phone/code.md
  _tutorials/en/client-sdk/app-to-phone/create-application.md
  _tutorials/en/client-sdk/app-to-phone/modify-ncco.md
  _tutorials/en/client-sdk/app-to-phone/run.md
  config/tutorials/en/app-to-phone.yml
Labels: review-app

#2669 Fixes additional missing links
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2672 Update iOS SDK v2.1.9 release notes
  .spelling
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: review-app

#2684 Update iOS SDK v2.1.10 release notes
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: review-app

#2674 DEVX 2496 Added Seen Receipt
  _tutorials_tabbed_content/client-sdk/guides/messaging/seen-receipt/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/seen-receipt/kotlin.md
Labels: review-app

#2676 DEVX 2497 Added utilising event snippets
  _documentation/en/client-sdk/in-app-messaging/guides/utilizing-events.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/utilizing-events/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/utilizing-events/javascript.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/utilizing-events/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/utilizing-events/objective-c.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/utilizing-events/swift.md
Labels: review-app

#2678 DEVX 2420 snippet add client sdk
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/ios.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/build-client/java.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/build-client/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/connection-listener/java.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/connection-listener/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/groovy.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/login/java.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/login/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/request-permissions/java.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/request-permissions/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/delegate/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/delegate/swift.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/import/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/import/swift.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/login/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/login/swift.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/permissions/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/permissions/swift.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/user/objective-c.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/ios/user/swift.md
  config/code_languages.yml
Labels: review-app

#2455 Update contrib guide
  app/views/contribute/guides/markdown-guide.md
  app/views/contribute/guides/tasks.md
  app/views/contribute/guides/tutorials.md
  config/redirects.yml
  public/assets/images/contributing/prereqs.png
  public/assets/images/contributing/task-example.png
Labels: review-app

#2691 DEVX-2422 Added Kotlin snippet to configure DataCenter
  _examples/client-sdk/dc-config/android.md
  _examples/client-sdk/dc-config/java.md
  _examples/client-sdk/dc-config/javascript.md
  _examples/client-sdk/dc-config/kotlin.md
  _examples/client-sdk/dc-config/swift.md
Labels: review-app

#2692 DEVX-2423 Added Kotlin snippet
  _examples/client-sdk/ice-server/android.md
  _examples/client-sdk/ice-server/ios.md
  _examples/client-sdk/ice-server/java.md
  _examples/client-sdk/ice-server/kotlin.md
Labels: review-app

#2694 More redirect fixes
  config/stitch-redirects.yml
Labels: review-app

#2696 update call-flow for type field for transfer events
  _documentation/en/voice/voice-api/guides/call-flow.md
Labels: review-app

#2695 RailsConf 2020 Couch Edition Landing Page
  config/landing_pages/e/railsconf2020.yml
Labels: review-app

#2659 [DEVX-2029] Filter tutorials by programming languages.
  app/controllers/use_case_controller.rb
  app/presenters/language.rb
  app/views/layouts/partials/_programming_languages_dropdown.html.erb
  app/views/tutorial/list.html.erb
  app/views/use_case/index.html.erb
Labels: review-app

#2701 [DEVX-2719] Bump nexmo-markdown-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2699 Devx 2490 snippets custom events
  _documentation/en/client-sdk/custom-events.md
  _tutorials_tabbed_content/client-sdk/custom-events/complete/java.md
  _tutorials_tabbed_content/client-sdk/custom-events/complete/kotlin.md
  _tutorials_tabbed_content/client-sdk/custom-events/creating/java.md
  _tutorials_tabbed_content/client-sdk/custom-events/creating/kotlin.md
  _tutorials_tabbed_content/client-sdk/custom-events/listening/java.md
  _tutorials_tabbed_content/client-sdk/custom-events/listening/kotlin.md
Labels: review-app

#2704 [DEVX-2029] Remove DotNet.
  app/presenters/language.rb
  app/views/layouts/partials/_programming_languages_dropdown.html.erb
Labels: review-app

#2705 move videos to bottom on railsconf landing page
  config/landing_pages/e/railsconf2020.yml
Labels: review-app

#2708 update android release-notes for v2.6.0
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#2707 Fix dependency tab and upgrade SDK version `2.5.0` -> `2.5.1`
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/groovy.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/kotlin.md
Labels: review-app

#2690 Bump volta.
  package.json
  yarn.lock
Labels: review-app

#2706 DEVX-2498 Added code snippets for inviting members (kotlin and java)
  _documentation/en/client-sdk/in-app-messaging/guides/inviting-members.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/invite/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/invite/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/invited/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/invited/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/joined/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/joined/kotlin.md
Labels: review-app

#2702 Client SDK redirects
  config/stitch-redirects.yml
Labels: review-app

#2715 Add Node snippet
  _examples/voice/answer-inbound-call-with-asr/node.yml
Labels: review-app

#2720 remove public reference to ASR
  _documentation/en/voice/voice-api/code-snippets/answer-inbound-call-with-asr.md
  _examples/voice/answer-inbound-call-with-asr/node.yml
  _examples/voice/answer-inbound-call-with-asr/ruby.yml
  config/redirects.yml
Labels: review-app

#2719 Bump markdown-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2723 Update Android Client SDK dependency version - Kotlin
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/kotlin.md
Labels: review-app

#2725 DEVX-2999 Add leave conversation snippets
  _tutorials_tabbed_content/client-sdk/guides/messaging/leave-conversation/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/leave-conversation/kotlin.md
Labels: review-app

#2724 Update Android Client SDK dependency version - groovy
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/groovy.md
Labels: review-app

#2726 Devx 2501 snippet make a call
  _tutorials_tabbed_content/client-sdk/guides/make-call/in-app/java.md
  _tutorials_tabbed_content/client-sdk/guides/make-call/in-app/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/make-call/listen-to-call-events/java.md
  _tutorials_tabbed_content/client-sdk/guides/make-call/listen-to-call-events/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/make-call/server-managed/java.md
  _tutorials_tabbed_content/client-sdk/guides/make-call/server-managed/kotlin.md
Labels: review-app

#2734 Add kotlin and groovy icons.
  Gemfile
  Gemfile.lock
  public/assets/images/brands/groovy.svg
  public/assets/images/brands/kotlin.svg
Labels: review-app

#2727 DEVX 2500 Added DTMF
  _tutorials_tabbed_content/client-sdk/guides/dtmf/receive/Kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/dtmf/receive/java.md
  _tutorials_tabbed_content/client-sdk/guides/dtmf/send/Kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/dtmf/send/java.md
  _tutorials_tabbed_content/client-sdk/guides/messaging/inviting-members/invited/kotlin.md
Labels: review-app

#2731 DEVX-2502 Receive a Call
  _tutorials_tabbed_content/client-sdk/guides/receive-call/answer/java.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/answer/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/hangup/java.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/hangup/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/listen-to-call-events/java.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/listen-to-call-events/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/receive-call/java.md
  _tutorials_tabbed_content/client-sdk/guides/receive-call/receive-call/kotlin.md
Labels: review-app

#2737 Add Developer Day banner
  app/views/layouts/partials/_notices.html.erb
Labels: review-app

#2738 Messages API Sandbox Callback retry behavior documentation
  _documentation/en/messages/concepts/messages-api-sandbox.md
Labels: review-app

#2739 addiing free to use note for messages sandbox
  _documentation/en/messages/concepts/messages-api-sandbox.md
Labels: review-app

#2721 update android release-notes for v2.6.1
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#2733 Devx 2503 snippet mute call member
  _tutorials_tabbed_content/client-sdk/guides/mute-call-member/java.md
  _tutorials_tabbed_content/client-sdk/guides/mute-call-member/javascript.md
  _tutorials_tabbed_content/client-sdk/guides/mute-call-member/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/mute-call-member/objective-c.md
  _tutorials_tabbed_content/client-sdk/guides/mute-call-member/swift.md
  _tutorials_tabbed_content/client-sdk/guides/unmute-call-member/java.md
  _tutorials_tabbed_content/client-sdk/guides/unmute-call-member/javascript.md
  _tutorials_tabbed_content/client-sdk/guides/unmute-call-member/kotlin.md
  _tutorials_tabbed_content/client-sdk/guides/unmute-call-member/objective-c.md
  _tutorials_tabbed_content/client-sdk/guides/unmute-call-member/swift.md
Labels: review-app

#2735 Devx 2504 snippet earmuff
  _tutorials_tabbed_content/client-sdk/guides/earmuff-call-member/java.md
  _tutorials_tabbed_content/client-sdk/guides/earmuff-call-member/kotlin.md
Labels: review-app

#2618 Rewrite tutorial to incorporate pagination and reformatted code.
  _tutorials/en/client-sdk/in-app-messaging/authenticate-users/javascript.md
  _tutorials/en/client-sdk/in-app-messaging/create-ui/javascript.md
  _tutorials/en/client-sdk/in-app-messaging/join-conversation/javascript.md
  _tutorials/en/client-sdk/in-app-messaging/show-message-history/javascript.md
Labels: review-app

#2689 Reports API doc changes and additions
  _documentation/en/reports/overview.md
  _tutorials/en/reports/check-report-status.md
  _tutorials/en/reports/create-report-postman.md
  _tutorials/en/reports/create-report.md
  _tutorials/en/reports/get-json-records.md
  config/tutorials/en/create-and-retrieve-a-report.yml
  config/tutorials/en/create-report-using-graphical-tools.yml
  config/tutorials/en/get-json-records-cli.yml
Labels: review-app

#2742 Fix initial docker-compose up experience
  Dockerfile
  docker-compose.yml
Labels: review-app

#2693 Add rake task to detect duplicate navigation weights
  lib/tasks/ci.rake
Labels: review-app

#2652 [DEVX-2685] Group bugnsag exceptions into `Missing Document` and `404…
  app/controllers/application_controller.rb
  app/services/not_found_notifier.rb
  spec/requests/markdown_spec.rb
  spec/services/not_found_notifier_spec.rb
Labels: review-app

#2744 Add check to make sure .ruby-version, Gemfile and Docker are in sync
  .github/workflows/ci.yml
  lib/tasks/ci.rake
Labels: review-app

#2745 Fix button location on Community page when there are no events
  app/views/static/default_landing/partials/_events.html.erb
  app/webpacker/stylesheets/layout/_community.scss
  lib/tasks/ci.rake
Labels: review-app

#2728 Update iOS SDK v2.2.0 release notes
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: review-app

#2750 update android release-notes for v2.6.2
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#2756 Added Vonage Developer Day landing page at /day
  app/views/layouts/partials/_notices.html.erb
  config/landing_pages/day.yml
Labels: review-app

#2758 add instruction on event landing page placement
  app/views/contribute/guides/landing-pages.md
Labels: review-app

#2746 NCCO - start and end date format is ISO 8601
  _documentation/en/voice/voice-api/ncco-reference.md
Labels: review-app

#2752 Update for changes to Dashboard
  _partials/reusable/create-a-nexmo-application.md
  _partials/reusable/link-facebook-to-nexmo.md
Labels: review-app
