Repository Nexmo/nexmo-developer, pull requests merged in 2020-03, with the labels that each got.

#2485 Update JS Release Notes for v6.0.8
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2486 Update SDK docs
  .repos/nexmo/conversation-docs/android/latest
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#2472 Upgrade serialize-javascript to ^2.1.1
  package.json
  yarn.lock
Labels: review-app

#2496 Add mising redirect for /tutorials/phone-number-validation.
  config/redirects.yml
Labels: review-app

#2495 update android release-notes for v2.4.0
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#2497 Fix links with redirects
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2491 Update fallback_answer_url behavior
  _documentation/en/voice/voice-api/webhook-reference.md
  _examples/concepts/guides/webhooks-setup/voice.md
Labels: review-app

#2480 Improve Verify Velocity Error Information
  _documentation/en/verify/guides/velocity-rules.md
Labels: review-app

#2500 Tony sms error codes
  _documentation/en/messaging/sms/overview.md
Labels: review-app

#2501 Add redirects for old Stitch guides
  config/stitch-redirects.yml
Labels: review-app

#2507 Reduce the size of diagrams in Subaccounts overview
  public/assets/images/subaccounts/account_balance.png
  public/assets/images/subaccounts/balance_transfer.png
  public/assets/images/subaccounts/credit_allocation.png
  public/assets/images/subaccounts/structure.png
Labels: review-app

#2510 Adds Bugsnag config to guide.
  .spelling
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/javascript.md
Labels: review-app

#2464 Remove constraints
  app/assets/config/manifest.js
  app/constraints/documentation_constraint.rb
  app/constraints/open_api_constraint.rb
  app/services/tutorial_list.rb
  app/views/dashboard/coverage.html.erb
  config/application.rb
  config/products.yml
Labels: review-app

#2517 Refer to Knowledge Base for list of IPs to whitelist
  _documentation/en/voice/sip/overview.md
Labels: review-app

#2255 DEVX-1863: Allow locale in url
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/constraints/documentation_constraint.rb
  app/constraints/locale_constraint.rb
  app/controllers/application_controller.rb
  app/controllers/markdown_controller.rb
  app/controllers/static_controller.rb
  app/controllers/tutorial_controller.rb
  app/controllers/use_case_controller.rb
  app/helpers/application_helper.rb
  app/javascript/src/application.css
  app/models/product.rb
  app/models/tutorial.rb
  app/presenters/navigation.rb
  app/presenters/sidenav.rb
  app/presenters/sidenav_item.rb
  app/presenters/sidenav_resolver.rb
  app/presenters/sidenav_subitem.rb
  app/services/redirector.rb
  app/views/extend/index.html.erb
  app/views/layouts/documentation.html.erb
  app/views/layouts/partials/_header.html.erb
  app/views/static/default_landing/partials/_tutorial.html.erb
  app/views/tutorial/index.html.erb
  app/views/tutorial/list.html.erb
  app/views/use_case/_index.html.erb
  app/views/use_case/index.html.erb
  app/views/use_case/list/plain.html.erb
  config/initializers/locale.rb
  config/locales/cn.yml
  config/products.yml
  config/routes.rb
  package.json
  spec/controllers/static_controller_spec.rb
  spec/models/tutorial_spec.rb
  spec/presenters/sidenav_item_spec.rb
  spec/presenters/sidenav_spec.rb
  spec/presenters/sidenav_subitem_spec.rb
  spec/requests/markdown_spec.rb
  spec/routing/markdown_spec.rb
  spec/routing/tutorials_spec.rb
  spec/routing/use_cases_spec.rb
  spec/services/redirector_spec.rb
  spec/views/static/default_landing/partials/_tutorial.html.erb_spec.rb
  yarn.lock
Labels: review-app

#2518 Update Configure Webhooks topic for new Dashboard
  _partials/reusable/configure-webhook-urls.md
Labels: review-app

#2521 Fix tutorials' urls.
  config/routes.rb
Labels: review-app

#2502 Add users to Account overview
  _documentation/en/account/overview.md
  public/assets/images/account/overview.png
  public/assets/images/account/overview_orig.png
  public/assets/images/account/users.svg
Labels: Do Not Merge, review-app

#2522 Cnam not cname
  _documentation/en/number-insight/guides/cnam.md
Labels: review-app

#2527 upgrade markdown renderer
  Gemfile
  Gemfile.lock
Labels: review-app

#2526 [CVE-2020-7598] Bump minimist and acorn.
  package.json
  yarn.lock
Labels: review-app

#2523 Update customizing-tts.md
  _documentation/en/voice/voice-api/guides/customizing-tts.md
Labels: review-app

#2539 Add missing redirects.
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2540 [DEVX-2461] Fix one errant SIP domain example
  _documentation/en/voice/sip/concepts/programmable-sip.md
Labels: review-app

#2541 Add missing redirects
  config/redirects.yml
  config/stitch-redirects.yml
Labels: review-app

#2533 Changes to Dashboard
  _documentation/en/account/guides/dashboard-management.md
  _documentation/en/account/overview.md
  _documentation/en/account/secret-management.md
  _documentation/en/account/subaccounts/overview.md
  _documentation/en/concepts/guides/glossary.md
  public/assets/images/account/overview.png
  public/assets/images/account/overview_orig.png
  public/assets/images/account/users.svg
Labels: Ready for Review, review-app

#2544 [DEVX-2466] Bump nexmo-markdown-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2556 [DEVX-2472] Fix code snippets inside tabs.
  Gemfile.lock
Labels: review-app

#2557 [DEVX-2473] Fix issue when a page has multiple code snippets tabs.
  app/webpacker/javascript/volta/volta.js
Labels: review-app

#2558 Added Greg Holmes to team.yml file
  config/team.yml
Labels: review-app

#2560 Fix admin panel.
  app/assets/stylesheets/active_admin.scss
Labels: review-app

#2561 [DEVX-1973] Update SDK dependency version and permission example
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
Labels: review-app

#2563 Test travis color
  .travis.yml
Labels: review-app

#2534 Use template namespace and name
  .spelling
  _documentation/en/messages/code-snippets/whatsapp/send-button-link.md
  _documentation/en/messages/code-snippets/whatsapp/send-button-quick-reply.md
  _documentation/en/messages/code-snippets/whatsapp/send-media-mtm.md
  _documentation/en/messages/code-snippets/whatsapp/send-mtm.md
Labels: review-app

#2528 Updated fallback note with error info
  _documentation/en/messages/concepts/whatsapp.md
Labels: review-app

#2565 Fix config for code snippet
  _examples/messages/whatsapp/send-mtm/curl.yml
Labels: review-app

#2559 Update App Overview
  _documentation/en/application/overview.md
Labels: review-app

#2566 Fixed manifest and simplified permissions
  _documentation/en/client-sdk/setup/add-sdk-to-your-app/android.md
Labels: review-app

#2569 Add unavailable-legal to API Errors
  app/views/api_errors/_error_example.html.erb
  config/api-errors.yml
Labels: review-app

#2570 Add link to JWT web app
  _partials/reusable/generate-a-jwt.md
Labels: review-app

#2577 Fix accessibility in navigation bar
  app/views/layouts/partials/_sidenav_item.html.erb
  app/views/layouts/partials/_sidenav_subitem.html.erb
Labels: review-app

#2576 Update JS Release Notes for v6.0.9
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#2579 Update SDK docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#2574 Use new version of nexmo-markdown-renderer.
  Gemfile
  Gemfile.lock
Labels: review-app

#2525 [DEVX-2444] Change footer links
  app/views/api_errors/_error_example.html.erb
  app/views/layouts/partials/_footer.html.erb
  app/webpacker/src/application.css
  app/webpacker/stylesheets/application.scss
  app/webpacker/stylesheets/layout/_footer.scss
  app/webpacker/stylesheets/objects/_icons.scss
  public/assets/fonts/icomoon.eot
  public/assets/fonts/icomoon.json
  public/assets/fonts/icomoon.svg
  public/assets/fonts/icomoon.ttf
  public/assets/fonts/icomoon.woff
Labels: review-app

#2585 update android release-notes for v2.5.0
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#2588 Bump octokit
  Gemfile.lock
Labels: review-app

#2591 Remove products as requested
  app/views/static/_products.html.erb
  spec/features/landing_page_spec.rb
Labels: review-app

#2504 Start adding some OpenAPI docs
  .spelling
  README.md
  _documentation/en/concepts/guides/openapi.md
  _documentation/en/concepts/guides/webhooks.md
  _documentation/en/concepts/overview.md
  _documentation/en/messaging/sms/code-snippets/before-you-begin.md
  _documentation/en/number-insight/code-snippets/before-you-begin.md
  _documentation/en/tools/ngrok.md
  _documentation/en/tools/postman.md
  _documentation/en/tools/prism.md
  _partials/reusable/configure-webhook-urls.md
  _tutorials/en/client-sdk/create-application.md
  _tutorials/en/olympus/test-webhook-server.md
  _tutorials/en/run-ngrok.md
  _use_cases/en/fraud-scoring-and-phone-number-verification.md
  _use_cases/en/interactive-voice-response.md
  _use_cases/en/local-numbers.md
  _use_cases/en/private-voice-communication.md
  _use_cases/en/voice-alerts.md
  app/presenters/sidenav_subitem.rb
  app/views/contribute/guides/platform.md
  app/views/static/documentation.md
  config/locales/en.yml
  config/navigation.yml
  config/products.yml
  config/redirects.yml
  public/assets/images/download-openapi3-button.png
  spec/presenters/sidenav_resolver_spec.rb
  spec/presenters/sidenav_subitem_spec.rb
Labels: review-app

#2596 Fix spelling mistake
  app/views/api/index.html.erb
Labels: review-app

#2597 Update copyright year
  LICENSE.md
  LICENSE.txt
Labels: review-app

#2600 Clarify that template must be in your namespace
  _documentation/en/messages/code-snippets/whatsapp/send-button-link.md
  _documentation/en/messages/code-snippets/whatsapp/send-button-quick-reply.md
  _documentation/en/messages/code-snippets/whatsapp/send-media-mtm.md
  _documentation/en/messages/code-snippets/whatsapp/send-mtm.md
  _documentation/en/messages/concepts/whatsapp.md
Labels: review-app

#2603 Update VAPI Websocket Docs
  _documentation/en/voice/voice-api/webhook-reference.md
  _examples/voice/guides/ncco-reference/connect/websocket-endpoint-connect.md
Labels: review-app
