Repository Nexmo/nexmo-developer, pull requests merged in 2020-11, with the labels that each got.

#3327 Verification with workflow java code snippet
  _examples/verify/send-verification-request-with-workflow/java.yml
Labels: review-app

#3325 PSD2 Code snippets
  _examples/verify/send-psd2-verification-request-with-workflow/java.yml
  _examples/verify/send-psd2-verification-request/java.yml
Labels: review-app

#3329 Add Feedback config file.
  config/feedback.yml
Labels: Do Not Merge, review-app

#3312 Devtv nov2
  custom/landing_pages/devtv.yml
Labels: review-app

#3331 Branding changes
  _documentation/en/account/subaccounts/overview.md
  _documentation/en/messages/code-snippets/message-status.md
  _documentation/en/messages/concepts/facebook.md
  _documentation/en/messages/concepts/whatsapp.md
  _documentation/en/messages/external-accounts/overview.md
Labels: review-app

#3332 Added Filippos to team.yml
  config/team.yml
Labels: review-app

#3333 More branding changes
  _documentation/en/index.md
  _documentation/en/tools/ngrok.md
  _documentation/en/tools/postman.md
  _documentation/en/tools/prism.md
  _partials/client-sdk/voice/inbound-pstn-application-webhook.md
  _partials/client-sdk/voice/javascript/login.md
  _partials/client-sdk/voice/link-nexmo-number.md
  _partials/client-sdk/voice/outbound-call-intro.md
  _partials/client-sdk/voice/outbound-pstn-application-webhook.md
  _partials/client-sdk/voice/pstn-nexmo-concepts.md
  _partials/client-sdk/voice/pstn-prerequisites.md
  _partials/reusable/beta-node-server-sdk-messages-dispatch.md
  _partials/reusable/configure-webhook-urls.md
  _partials/reusable/create-a-nexmo-application.md
  _partials/reusable/generate-a-jwt.md
  _partials/reusable/link-facebook-to-nexmo.md
  _partials/reusable/prereqs.md
  _partials/stitch/guides/enable-screenshare/javascript.md
  _partials/stitch/guides/enable-video/javascript.md
Labels: review-app

#3334 Rebrand Nexmo number
  _documentation/en/conversation/guides/event-flow.md
  _documentation/en/voice/voice-api/code-snippets/connect-an-inbound-call.md
  _documentation/en/voice/voice-api/code-snippets/connect-callers-into-a-conference.md
  _documentation/en/voice/voice-api/code-snippets/handle-user-input-with-asr.md
  _documentation/en/voice/voice-api/code-snippets/handle-user-input-with-dtmf.md
  _documentation/en/voice/voice-api/code-snippets/receive-an-inbound-call.md
  _documentation/en/voice/voice-api/code-snippets/record-a-conversation.md
  _documentation/en/voice/voice-api/code-snippets/record-a-message.md
  _documentation/en/voice/voice-api/code-snippets/track-ncco-progress.md
  _documentation/en/voice/voice-api/guides/endpoints.md
  _documentation/en/voice/voice-api/guides/numbers.md
  _partials/client-sdk/voice/link-nexmo-number.md
  _tutorials/en/buy-nexmo-number.md
  _tutorials/en/client-sdk/phone-to-app/create-webhook-server/javascript.md
  _tutorials/en/client-sdk/phone-to-app/run/javascript.md
  _tutorials/en/link-nexmo-number.md
  _tutorials/en/messages-dispatch/create-application.md
  _use_cases/en/add-a-call-whisper-to-an-inbound-call.md
  _use_cases/en/asr-use-case-voice-bot.md
  _use_cases/en/call-tracking.md
  _use_cases/en/client-sdk-click-to-call.md
  _use_cases/en/contact-center-client-sdk.md
  _use_cases/en/interactive-voice-response.md
  _use_cases/en/real-time-feed.md
  _use_cases/en/receiving-concat-sms.md
  _use_cases/en/retrieve-conversation-details.md
  _use_cases/en/sms-customer-support.md
  _use_cases/en/trancribe-amazon-api.md
  _use_cases/en/two-way-sms-for-customer-engagement.md
  _use_cases/en/voice-alerts.md
  _use_cases/en/voice-call-websocket-node.md
  _use_cases/en/voice-call-websocket-python.md
Labels: review-app

#3310 Voice Signed Callbacks DevPreview
  _documentation/en/voice/voice-api/guides/signed-webhooks.md
  config/navigation.yml
Labels: review-app

#3337 Update image alt text.
  custom/landing_pages/hacktoberfest.yml
Labels: review-app

#3336 Voicemail tutorial for .NET
  _tutorials/en/voice-api/add-recording-route.md
  _tutorials/en/voice-api/add-voicemail-answer-route.md
  _tutorials/en/voice-api/configure-aspnet-app.md
  config/tutorials/en/build-voicemail-dotnet.yml
Labels: review-app

#3339 Add self to team page
  config/team.yml
Labels: review-app

#3338 Rebrand Nexmo -> Vonage in tutorials
  _partials/client-sdk/voice/android/login-intro.md
  _partials/stitch/guides/enable-screenshare/javascript.md
  _partials/stitch/guides/enable-video/javascript.md
  _tutorials/en/client-sdk/android-shared/create-user-alice.md
  _tutorials/en/client-sdk/app-to-app/create-application.md
  _tutorials/en/client-sdk/app-to-app/create-project/objective_c.md
  _tutorials/en/client-sdk/app-to-app/create-users.md
  _tutorials/en/client-sdk/app-to-app/create-webhook-server.md
  _tutorials/en/client-sdk/app-to-phone/create-application.md
  _tutorials/en/client-sdk/app-to-phone/create-ncco.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server.md
  _tutorials/en/client-sdk/app-to-phone/js-code.md
  _tutorials/en/client-sdk/app-to-phone/make-call/java.md
  _tutorials/en/client-sdk/app-to-phone/make-call/kotlin.md
  _tutorials/en/client-sdk/app-to-phone/project/objective_c.md
  _tutorials/en/client-sdk/app-to-phone/project/swift.md
  _tutorials/en/client-sdk/create-application.md
  _tutorials/en/client-sdk/create-users.md
  _tutorials/en/client-sdk/in-app-messaging/create-application.md
  _tutorials/en/client-sdk/in-app-messaging/create-project/objective_c.md
  _tutorials/en/client-sdk/in-app-messaging/create-users/javascript.md
  _tutorials/en/client-sdk/in-app-messaging/create-users/swift.md
  _tutorials/en/client-sdk/phone-to-app/create-application.md
  _tutorials/en/client-sdk/phone-to-app/project/objective_c.md
  _tutorials/en/client-sdk/phone-to-app/project/swift.md
  _tutorials/en/create-nexmo-account.md
  _tutorials/en/install-android-studio.md
  _tutorials/en/install-nexmo-cli-beta.md
  _tutorials/en/install-nexmo-cli.md
  _tutorials/en/install-node-client-sdk-beta.md
  _tutorials/en/install-node-sdk-beta.md
  _tutorials/en/install-nodejs.md
  _tutorials/en/install-xcode.md
  _tutorials/en/messages-dispatch/configure-webhooks.md
  _tutorials/en/messages-dispatch/link-facebook-page.md
  _tutorials/en/messages-dispatch/send-viber-message.md
  _tutorials/en/reports/check-report-status.md
  _tutorials/en/reports/create-report-postman.md
  _tutorials/en/reports/create-report.md
  _tutorials/en/reports/get-json-records.md
  _tutorials/en/run-ngrok.md
  _tutorials/en/sms-api/handle-form-post.md
  _tutorials/en/sms-api/install-nexmo-python.md
  _tutorials/en/sms-api/send-sms-from-repl.md
  _tutorials/en/sms-api/set-up-sms-flask.md
  _tutorials/en/verify/2fa-ruby-send-verify-request.md
  _tutorials/en/verify/stepup-auth-create-node-application.md
  _tutorials/en/verify/stepup-auth-init-dependencies.md
  _tutorials/en/verify/stepup-auth-send-verification-request.md
Labels: review-app

#3340 Update Luke's Twitter handle
  config/team.yml
Labels: review-app

#3341 Remove Adam Culp
  config/team.yml
Labels: review-app

#3335 added week.init()
  custom/landing_pages/devtv.yml
Labels: review-app

#3349 Fix Python dependency
  _examples/verify/search-verification-request/python.yml
  _examples/voice/make-an-outbound-call-with-ncco/python.yml
  _examples/voice/transfer-a-call-inline-ncco/python.yml
Labels: review-app

#3352 Bump station.
  Gemfile
  Gemfile.lock
Labels: review-app

#3351 Python config fixes
  _examples/messages/inbound-message/python.yml
  _examples/messages/message-status/python.yml
  _examples/verify/check-verification-request/python.yml
  _examples/verify/search-verification-request/python.yml
Labels: review-app

#3353 Rebrand Application Overview diagram
  _documentation/en/application/overview.md
  public/images/nexmo_application_v2.png
  public/images/vonage_application_v2.png
Labels: review-app

#3354 Make JWT tool more obvious
  _documentation/en/concepts/guides/authentication.md
  _documentation/en/getting-started/overview.md
  _documentation/en/tools/jwt-generator.md
  _documentation/en/voice/voice-api/code-snippets/before-you-begin.md
Labels: help wanted, review-app

#3360 Update SDK Docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#3359 Update JS Release Notes for v6.0.17
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#3362 Bump station fix review apps
  Gemfile
  Gemfile.lock
  Procfile
Labels: review-app

#3363 Bump station.
  Gemfile
  Gemfile.lock
Labels: review-app

#3358 Rebrand 2FA API diagram
  _documentation/en/messaging/us-short-codes/guides/2fa.md
  _documentation/en/messaging/us-short-codes/guides/alerts.md
  _documentation/en/messaging/us-short-codes/guides/campaign-subscription-management.md
  public/images/messaging/2fa/2fa_api_workflow.png
  public/images/messaging/alerts/alerts_workflow.png
  public/images/messaging/alerts/campaign_mgmt_workflow.png
  public/images/workflow_2fa.svg
  public/images/workflow_campaign_subscription_management.svg
  public/images/workflow_sending_event_based_alerts.svg
Labels: Ready for Review, review-app

#3364 Rebrand Conversion API diagram
  _documentation/en/messaging/conversion-api/overview.md
  public/images/messaging/conversion/conversion_api_workflow.png
  public/images/workflow_conversion_api.svg
Labels: review-app

#3344 Added a blurb to all relevant pages where USSC deprecation needs to be displayed.
  _api/sms/us-short-codes/2fa.md
  _api/sms/us-short-codes/alerts/sending.md
  _api/sms/us-short-codes/alerts/subscription.md
  _documentation/en/concepts/guides/glossary.md
  _documentation/en/dispatch/code-snippets/send-an-mms-with-failover.md
  _documentation/en/messages/code-snippets/mms/send-mms.md
  _documentation/en/messaging/us-short-codes/guides/2fa.md
  _documentation/en/messaging/us-short-codes/guides/alerts.md
  _documentation/en/messaging/us-short-codes/guides/campaign-subscription-management.md
  _documentation/en/messaging/us-short-codes/overview.md
  _documentation/en/numbers/guides/enable-2fa.md
  _documentation/en/numbers/guides/event-alerts.md
Labels: SMS, review-app

#3356 updated content for weeks nov16 - december 4
  custom/landing_pages/devtv.yml
Labels: review-app

#3367 Rebrand Dispatch API overview diagram
  public/images/messages-dispatch-overview.png
Labels: review-app

#3369 Rebrand SIP Workflow diagram
  public/images/workflow_sip_connect.png
Labels: review-app

#3370 Remove Nexmo from tutorial title
  config/tutorials/en/number-insight-api-aspnet.yml
Labels: review-app

#3371 updated content for MWM nov17
  custom/landing_pages/devtv.yml
Labels: review-app

#3326 ASR Java Code Snippet
  _examples/voice/handle-user-input-with-asr/java.yml
  _examples/voice/handle-user-input-with-dtmf/java.yml
Labels: Ready for Review, dependencies, review-app

#3373 remove beta label for ASR
  _documentation/en/voice/voice-api/guides/asr.md
  config/navigation.yml
Labels: review-app

#3375 Rebrand Conversation API diagrams
  public/images/conversation-api/call-forward-conversation.png
  public/images/conversation-api/channels-media.png
  public/images/conversation-api/conv-app-setup.png
  public/images/conversation-api/conversation-application.png
  public/images/conversation-api/conversation-detail.png
Labels: review-app

#3377 Bump station
  .github/workflows/ci.yml
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: review-app

#3380 Update Android SDK v2.8.0 release notes
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#3382 Remove Number Insight Fraud Detection use case
  _use_cases/en/fraud-scoring-and-phone-number-verification.md
  config/redirects.yml
Labels: review-app

#3383 Update JS Release Notes for v6.0.18
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#3384 Update SDK Docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#3385 Rebrand Account and Subaccount API diagrams
  public/images/account/overview.png
  public/images/subaccounts/month_end_balance_transfer.png
  public/images/subaccounts/shared_balance.png
Labels: review-app

#3378 DEVX-4904 VAPI Configurable Webhook Timeouts
  _examples/concepts/guides/webhooks-setup/voice.md
  public/images/concepts/guides/db_voice_webhook_timeouts.png
Labels: review-app

#3389 DEVX-3102 making open API and postman more obvious
  _documentation/en/concepts/guides/openapi.md
  _documentation/en/getting-started/overview.md
  _documentation/en/tools/postman.md
Labels: review-app

#3390 Fix OpenAPI spelling in Getting Started
  _documentation/en/getting-started/overview.md
Labels: review-app

#3393 Update iOS SDK v2.5.0 release notes
  _documentation/en/client-sdk/sdk-documentation/ios/release-notes.md
Labels: review-app

#3388 content updated for week of november 23
  custom/landing_pages/devtv.yml
Labels: review-app

#3392 devx-4905
  _documentation/en/application/overview.md
Labels: review-app

#3398 increment version of Station
  Gemfile
  Gemfile.lock
Labels: review-app

#3399 add code snippet variables config
  config/code_snippet_variables.yml
Labels: review-app

#3396 Update JS Release Notes for v6.0.19
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#3400 Update SDK Docs
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
Labels: review-app

#3402 Add specs + bump station
  .github/workflows/ci.yml
  .rspec
  .ruby-version
  Gemfile
  Gemfile.lock
  config/redirects.yml
  spec/factories/events.rb
  spec/factories/sessions.rb
  spec/factories/users.rb
  spec/features/admin_spec.rb
  spec/features/careers_spec.rb
  spec/features/community_spec.rb
  spec/features/extend_spec.rb
  spec/features/landing_spec.rb
  spec/features/team_spec.rb
  spec/requests/store_spec.rb
  spec/spec_helper.rb
Labels: review-app

#3291 Smartling Translations Workflow
  .github/workflows/smartling_downloader.yml
  .github/workflows/smartling_uploader_180_days.yml
  .github/workflows/smartling_uploader_5_days.yml
  config/products.yml
Labels: review-app

#3403 Cross-reference to webhook timeouts info
  _examples/concepts/guides/webhooks-setup/voice.md
Labels: review-app
