Repository Nexmo/nexmo-developer, pull requests merged in 2020-10, with the labels that each got.

#3218 Hacktoberfest
  custom/landing_pages/hacktoberfest.yml
Labels: review-app

#3224 Enable review apps for forks
  .github/workflows/pull_request-pr-edited.yml
Labels: review-app

#3227 Remove pull_request event
  .github/workflows/pull_request-pr-edited.yml
Labels: review-app

#3233 Adding Voyager Profile for Mary Jo Staebler
  custom/landing_pages/voyagers.yml
Labels: review-app

#3217 Add voyager information
  custom/landing_pages/voyagers.yml
Labels: review-app

#3235 Fixed cases for Nexmo
  _documentation/en/conversation/concepts/application.md
  _documentation/en/voice/voice-api/code-snippets/connect-an-inbound-call.md
  _use_cases/en/interactive-voice-response.md
  _use_cases/en/retrieve-conversation-details.md
Labels: hacktoberfest

#3230 Fix case of GitHub
  README.md
  Runbook.md
  _extend/converse-ai.md
  _tutorials/en/join-github.md
Labels: hacktoberfest

#3229 Added Syntax Highlighting in all the Code Fences.
  README.md
Labels: hacktoberfest

#3234 docs: :pencil: Convert SMS API blog post to tutorial
  _tutorials/en/sms-api/add-send-sms-view.md
  _tutorials/en/sms-api/handle-form-post.md
  _tutorials/en/sms-api/install-nexmo-python.md
  _tutorials/en/sms-api/run-flask-server.md
  _tutorials/en/sms-api/send-sms-from-repl.md
  _tutorials/en/sms-api/set-up-sms-flask.md
  config/tutorials/en/send-sms-with-flask.yml
Labels: hacktoberfest, review-app

#3243 Add cURL code snippet for transferring a call with inline NCCO
  _examples/voice/transfer-a-call-inline-ncco/curl.yml
Labels: review-app

#3231 Updates for Java submodules
  _examples/messaging/sms/delivery-receipts/java.yml
  _examples/messaging/sms/receiving-an-sms/java.yml
  _examples/messaging/sms/send-an-sms-with-unicode/java.yml
  _examples/number-insight/async-callback/java.yml
  _examples/number-insight/async-trigger/java.yml
  _examples/numbers/update/java.yml
  _examples/verify/cancel-verification-request/java.yml
  _examples/verify/search-verification-request/java.yml
  _examples/verify/trigger-next-verification-process/java.yml
  _examples/voice/connect-an-inbound-call/java.yml
  _examples/voice/connect-callers-to-a-conference/java.yml
  _examples/voice/download-a-recording/java.yml
  _examples/voice/earmuff-a-call/java.yml
  _examples/voice/handle-user-input-with-dtmf/java.yml
  _examples/voice/make-an-outbound-call-with-ncco/java.yml
  _examples/voice/make-an-outbound-call/java.yml
  _examples/voice/mute-a-call/java.yml
  _examples/voice/play-an-audio-stream-into-a-call/java.yml
  _examples/voice/play-dtmf-into-a-call/java.yml
  _examples/voice/play-tts-into-a-call/java.yml
  _examples/voice/receive-an-inbound-call/java.yml
  _examples/voice/record-a-call-with-split-audio/java.yml
  _examples/voice/record-a-call/java.yml
  _examples/voice/record-a-conversation/java.yml
  _examples/voice/record-a-message/java.yml
  _examples/voice/retrieve-info-for-a-call/java.yml
  _examples/voice/retrieve-info-for-all-calls/java.yml
  _examples/voice/track-ncco-progress/java.yml
  _examples/voice/transfer-a-call/java.yml
Labels: review-app

#3239 Correct homophone
  Runbook.md
Labels: hacktoberfest

#3255 Fixed Typos in Runbook.md
  Runbook.md
Labels: hacktoberfest

#3251 Hacktoberfest
  custom/landing_pages/devtv.yml
  custom/landing_pages/hacktoberfest.yml
Labels: review-app

#3257 moving tools page to Vonage org
  custom/landing_pages/tools.yml
Labels: review-app

#3254 adding tutorial for sending an SMS with asp.net
  .spelling
  _tutorials/en/configure-aspdotnet-app.md
  _tutorials/en/install-dotnet-core.md
  _tutorials/en/run-dotnet-app.md
  _tutorials/en/sms-api/add-sms-controller.md
  _tutorials/en/sms-api/create-send-sms-model.md
  _tutorials/en/sms-api/create-send-sms-view.md
  _tutorials/en/sms-api/create-sms-csproj.md
  _tutorials/en/sms-api/install-vonage-dotnet.md
  _tutorials/en/sms-api/manage-startup-route.md
  config/tutorials/en/send-sms-with-dotnet.yml
Labels: review-app

#3261 Update to use the Station gem
  Gemfile
  Gemfile.lock
Labels: review-app

#3259 Add voyager (Gabriel Cruz)
  custom/landing_pages/voyagers.yml
Labels: review-app

#3263 Update JS Docs to v6.0.16
  .repos/nexmo/conversation-docs/js/Application.html
  .repos/nexmo/conversation-docs/js/Conversation.html
  .repos/nexmo/conversation-docs/js/ConversationsPage.html
  .repos/nexmo/conversation-docs/js/EventsPage.html
  .repos/nexmo/conversation-docs/js/ImageEvent.html
  .repos/nexmo/conversation-docs/js/Media.html
  .repos/nexmo/conversation-docs/js/Member.html
  .repos/nexmo/conversation-docs/js/NXMCall.html
  .repos/nexmo/conversation-docs/js/NXMEvent.html
  .repos/nexmo/conversation-docs/js/NexmoApiError.html
  .repos/nexmo/conversation-docs/js/NexmoClient.html
  .repos/nexmo/conversation-docs/js/NexmoClientError.html
  .repos/nexmo/conversation-docs/js/TextEvent.html
  .repos/nexmo/conversation-docs/js/application.js.html
  .repos/nexmo/conversation-docs/js/classes.list.html
  .repos/nexmo/conversation-docs/js/conversation.js.html
  .repos/nexmo/conversation-docs/js/events_image_event.js.html
  .repos/nexmo/conversation-docs/js/events_nxmEvent.js.html
  .repos/nexmo/conversation-docs/js/events_text_event.js.html
  .repos/nexmo/conversation-docs/js/handlers_conversation_events.js.html
  .repos/nexmo/conversation-docs/js/index.html
  .repos/nexmo/conversation-docs/js/member.js.html
  .repos/nexmo/conversation-docs/js/modules_errors_emitter.js.html
  .repos/nexmo/conversation-docs/js/modules_media.js.html
  .repos/nexmo/conversation-docs/js/modules_nxmCall.js.html
  .repos/nexmo/conversation-docs/js/modules_rtc_helper.js.html
  .repos/nexmo/conversation-docs/js/modules_rtcstats_rtcstats.js.html
  .repos/nexmo/conversation-docs/js/nexmoClientError.js.html
  .repos/nexmo/conversation-docs/js/pages_conversations_page.js.html
  .repos/nexmo/conversation-docs/js/pages_events_page.js.html
  .repos/nexmo/conversation-docs/js/pages_page.js.html
  .repos/nexmo/conversation-docs/js/quicksearch.html
  .repos/nexmo/conversation-docs/js/sdk.js.html
  .repos/nexmo/conversation-docs/js/utils.js.html
  _documentation/en/client-sdk/sdk-documentation/javascript/release-notes.md
Labels: review-app

#3265 delete previous week content
  custom/landing_pages/devtv.yml
Labels: review-app

#3264 Added additional spacing between Voyagers profiles
  custom/landing_pages/voyagers.yml
Labels: review-app

#3267 Hacktoberfest oct13
  custom/landing_pages/devtv.yml
  custom/landing_pages/hacktoberfest.yml
Labels: review-app

#3271 pointing at the correct badges
  custom/landing_pages/tools.yml
Labels: review-app

#3280 Bump Station version
  Gemfile
  Gemfile.lock
Labels: review-app

#3284 Add new products to product list.
  _documentation/en/reports/code-snippets/before-you-begin.md
  _documentation/en/reports/code-snippets/create-async-report.md
  _documentation/en/reports/code-snippets/load-records-sync-dates.md
  _documentation/en/reports/code-snippets/load-records-sync-id.md
Labels: review-app

#3286 DEVX-4177 Update push tutorial
  _documentation/en/client-sdk/setup/set-up-push-notifications/android.md
  _tutorials/en/client-sdk/phone-to-app/permissions/java.md
  _tutorials/en/client-sdk/phone-to-app/permissions/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/groovy.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/dependencies/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/request-permissions/java.md
  _tutorials_tabbed_content/client-sdk/setup/add-sdk/android/request-permissions/kotlin.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/android/dependencies/groovy.md
  _tutorials_tabbed_content/client-sdk/setup/push-notifications/android/dependencies/kotlin.md
  public/screenshots/setup/client-sdk/set-up-push-notifications/firebase-generate-new-private-key.png
  public/screenshots/setup/client-sdk/set-up-push-notifications/firebase-token.png
Labels: review-app

#3282 Receive SMS & DLR .NET tutorials
  _tutorials/en/configure-account-webhooks.md
  _tutorials/en/run-dotnet-app.md
  _tutorials/en/sms-api/add-dlr-route.md
  _tutorials/en/sms-api/add-sms-controller-receive.md
  _tutorials/en/sms-api/create-send-sms-model.md
  config/tutorials/en/receive-sms-dotnet.yml
  config/tutorials/en/sms-dlr-with-dotnet.yml
Labels: review-app

#3283 Messages artwork update
  _documentation/en/messages/overview.md
  public/images/messages-overview.png
Labels: review-app

#3287 Add 204 No Content to inbound SMS guide
  _documentation/en/messaging/sms/guides/inbound-sms.md
Labels: review-app

#3293 fixed link to webhook section
  _documentation/en/messaging/sms/code-snippets/delivery-receipts.md
  _documentation/en/messaging/sms/code-snippets/receiving-an-sms.md
Labels: review-app

#3289 updated calendar for oct19, removed previous week, added content for …
  custom/landing_pages/devtv.yml
Labels: review-app

#3219 New Column for Discover Voyagers
  custom/landing_pages/voyagers.yml
Labels: review-app

#3281 Add voyager - Henry Shepherdson
  custom/landing_pages/voyagers.yml
Labels: review-app

#3296 Corrected wrong heading in Kotlin app-to-app tutorial task
  _tutorials/en/client-sdk/app-to-app/receive-call/kotlin.md
Labels: Ready for Review, review-app

#3298 Add voyager - Naomi Pentrel
  custom/landing_pages/voyagers.yml
Labels: review-app

#3297 Adding stream audio with dotnet tutorial
  .spelling
  _tutorials/en/install-nexmo-cli.md
  _tutorials/en/voice-api/add-make-call-action-streamed-audio.md
  _tutorials/en/voice-api/add-receive-call-route-stream-audio.md
  _tutorials/en/voice-api/add-voice-view.md
  _tutorials/en/voice-api/configure-aspnet-app.md
  _tutorials/en/voice-api/create-voice-controller.md
  _tutorials/en/voice-api/create-voice-csproj.md
  _tutorials/en/voice-api/create-vonage-application.md
  _tutorials/en/voice-api/install-vonage-dotnet.md
  _tutorials/en/voice-api/manage-startup-route.md
  config/tutorials/en/play-audio-into-call-dotnet.yml
Labels: review-app

#3299 Configure new menu items in Contributors' Guide
  config/locales/en.yml
Labels: Ready for Review, review-app

#3304 Remove deprecated feature
  _documentation/en/numbers/guides/payments.md
Labels: review-app

#3302 Fix incorrect line numbers
  _examples/voice/make-an-outbound-call-with-ncco/python.yml
Labels: review-app

#3306 Rebrand Before You Begin pages
  _documentation/en/dispatch/code-snippets/before-you-begin.md
  _documentation/en/messages/code-snippets/before-you-begin.md
  _documentation/en/messaging/sms/code-snippets/before-you-begin.md
  _documentation/en/number-insight/code-snippets/before-you-begin.md
  _documentation/en/verify/code-snippets/before-you-begin.md
  _documentation/en/voice/voice-api/code-snippets/before-you-begin.md
Labels: review-app

#3307 Update Android SDK v2.7.1 release notes
  _documentation/en/client-sdk/sdk-documentation/android/release-notes.md
Labels: review-app

#3309 Change Nexmo refs in Code Snippet pages to Vonage
  _documentation/en/account/code-snippets/account-balance.md
  _documentation/en/account/code-snippets/configure-account.md
  _documentation/en/dispatch/code-snippets/create-an-application.md
  _documentation/en/messages/code-snippets/messenger/send-template.md
  _documentation/en/messages/code-snippets/whatsapp/send-audio.md
  _documentation/en/messages/code-snippets/whatsapp/send-button-link.md
  _documentation/en/messages/code-snippets/whatsapp/send-button-quick-reply.md
  _documentation/en/messages/code-snippets/whatsapp/send-contact.md
  _documentation/en/messages/code-snippets/whatsapp/send-file.md
  _documentation/en/messages/code-snippets/whatsapp/send-image.md
  _documentation/en/messages/code-snippets/whatsapp/send-location.md
  _documentation/en/messages/code-snippets/whatsapp/send-media-mtm.md
  _documentation/en/messages/code-snippets/whatsapp/send-mtm.md
  _documentation/en/messages/code-snippets/whatsapp/send-text.md
  _documentation/en/messages/code-snippets/whatsapp/send-video.md
  _documentation/en/messaging/sms/code-snippets/delivery-receipts.md
  _documentation/en/messaging/sms/code-snippets/receiving-an-sms.md
  _documentation/en/messaging/sms/code-snippets/send-an-sms-with-unicode.md
  _documentation/en/messaging/sms/code-snippets/send-an-sms.md
  _documentation/en/number-insight/code-snippets/number-insight-advanced-async.md
  _documentation/en/number-insight/code-snippets/number-insight-advanced-sync.md
  _documentation/en/number-insight/code-snippets/number-insight-basic.md
  _documentation/en/numbers/code-snippets/buy.md
  _documentation/en/numbers/code-snippets/cancel.md
  _documentation/en/numbers/code-snippets/list-owned.md
  _documentation/en/numbers/code-snippets/search-available.md
  _documentation/en/numbers/code-snippets/update.md
  _documentation/en/verify/code-snippets/check-verify-request.md
  _documentation/en/verify/code-snippets/search-verify-request.md
  _documentation/en/verify/code-snippets/send-verify-psd2-request-with-workflow.md
  _documentation/en/verify/code-snippets/send-verify-psd2-request.md
  _documentation/en/verify/code-snippets/send-verify-request-with-workflow.md
  _documentation/en/verify/code-snippets/send-verify-request.md
  _documentation/en/verify/code-snippets/trigger-next-verification-process.md
Labels: review-app

#3311 show content updated for week of november 9th
  custom/landing_pages/devtv.yml
Labels: review-app

#3301 CCI Guide
  _documentation/en/voice/voice-api/guides/cci.md
  public/images/voice-api/cci_analytics.png
  public/images/voice-api/cci_bot.png
  public/images/voice-api/cci_bot_transfer.png
  public/images/voice-api/cci_ivr.png
  public/images/voice-api/cci_ivr_connect.png
  public/images/voice-api/cci_outbound.png
Labels: review-app

#3313 Added Voyager FAQ, Changed order of content blocks
  custom/landing_pages/voyagers.yml
Labels: review-app

#3314 Make text REST API a link
  _documentation/en/voice/voice-api/guides/dtmf.md
Labels: review-app

#3317 updated for Hacktoberfest Finale
  custom/landing_pages/devtv.yml
Labels: review-app

#3319 DEVX-4734 Update snippet
  _tutorials/en/client-sdk/android-shared/authenticate-alice-and-bob/kotlin.md
  _tutorials/en/client-sdk/android-shared/authenticate-alice/kotlin.md
Labels: review-app

#3321 Corrected typo
  README.md
Labels: hacktoberfest

#3322 DEVX-4687 Auto-redact fix wording
  _documentation/en/messaging/sms/message-privacy.md
  _documentation/en/redact/overview.md
Labels: review-app

#3324 Voice CCI Guide Link to Vonage AI Fix
  _documentation/en/voice/voice-api/guides/cci.md
Labels: review-app
