Repository Nexmo/nexmo-developer, pull requests merged in 2021-08, with the labels that each got.

#3771 Voice API ASR Speech Start Timeout Upgrade
  _documentation/en/voice/voice-api/ncco-reference.md
Labels: review-app

#3773 calendar update for the week
  custom/landing_pages/devtv.yml
Labels: review-app

#3776 add number to app to phone
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server/java.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server/javascript.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server/kotlin.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server/objective_c.md
  _tutorials/en/client-sdk/app-to-phone/create-webhook-server/swift.md
  config/tutorials/en/app-to-phone/java.yml
  config/tutorials/en/app-to-phone/javascript.yml
  config/tutorials/en/app-to-phone/kotlin.yml
  config/tutorials/en/app-to-phone/objective_c.yml
  config/tutorials/en/app-to-phone/swift.yml
Labels: review-app, Do Not Merge

#3777 Correct iOS app to app tutorials
  _tutorials/en/client-sdk/app-to-app/call-ui/objective_c.md
  _tutorials/en/client-sdk/app-to-app/call-ui/swift.md
  _tutorials/en/client-sdk/app-to-app/place-call/objective_c.md
  _tutorials/en/client-sdk/app-to-app/place-call/swift.md
  _tutorials/en/client-sdk/app-to-app/receive-call/objective_c.md
  _tutorials/en/client-sdk/app-to-app/receive-call/swift.md
  _tutorials/en/client-sdk/phone-to-app/receive-call/objective_c.md
  _tutorials/en/client-sdk/phone-to-app/receive-call/swift.md
Labels: review-app

#3779 add mofi to devrel team
  config/team.yml
Labels: review-app

#3767 Payments over the Phone Guide
  .spelling
  _documentation/en/voice/voice-api/guides/payments.md
  _documentation/en/voice/voice-api/ncco-reference.md
  _documentation/en/voice/voice-api/webhook-reference.md
  public/images/voice-api/payments_integration.png
Labels: WIP - Don't Merge, review-app

#3782 Voice Payments Minor Fixes
  _documentation/en/voice/voice-api/guides/payments.md
  config/navigation.yml
Labels: review-app

#3783 added Cory show for the week
  custom/landing_pages/devtv.yml
Labels: review-app

#3785 new week, updated calendar
  custom/landing_pages/devtv.yml
Labels: review-app
